### ISSUE TITLE
[TAREA 0]  Duda contactos estrechos y modelamiento

### ISSUE THREAD

**Issue by isiguelfand** [IIC2133-PUC/2021-1#10]
Hola! No me quedó claro que significa  "un contacto estrecho solo puede aparecer una vez en el problema" en la descripción de la clase Persona. Por lo que veo en las clases de python, creo que si una persona es contacto estrecho de dos contagiados, entonces habría que instanciarla dos veces, ya que estaría en dos listas ligadas. Se refiere a que esto no puede ocurrir?

**Comment by fadediego** [comment]
Hola!

Como dices, una persona no aparecerá en dos listas de contactos estrechos. Viéndolo como un árbol, una persona no tendrá dos padres.

Saludos!

**Comment by Brocoleta** [comment]
El contacto estrecho solo es padre-hijo o también son contactos estrechos los next y prev de un nodo?

**Comment by fadediego** [comment]
Hola @Brocoleta,
Solo los hijos. Si un nodo da positivo, sus hijos son los que pasan a sospechoso en espera. Sus nodos hermanos no.

Saludos.
