### ISSUE TITLE
[Duda C] gcc no reconoce las funciones de png.h

### ISSUE THREAD

**Issue by PDominguezW** [IIC2133-PUC/2021-1#101]
Al intentar compilar con gcc, el programa muestra 'undefined reference to `png_create_read_struct'

**Comment by nmcin** [comment]
Puedes compilar con `make`, es lo más simple y así lo haremos nosotros al corregir. Sin embargo, si quieres compilar algo con gcc deberás agregar el flag `-lpng`, para que tu programa carge dinámicamente la librería png del sistema.

**Comment by PDominguezW** [comment]
Muchas gracias, ahí funciono.
