### ISSUE TITLE
Duda Ayudantía 2 Problema 1

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2133-PUC/2021-1#102]
Hola! Estaba viendo la ayudantía 2 y no entendí en este paso por qué T(2^k-i) se reemplaza por 1
![Captura de pantalla 2021-04-14 a la(s) 15 47 15](https://user-images.githubusercontent.com/48481963/114770095-0b1bcc80-9d39-11eb-8c2a-0f82886af07f.png)
Y tampoco entendí por qué T(2n) sería igual a 2n * log(2n) + 2n
![Captura de pantalla 2021-04-14 a la(s) 15 47 26](https://user-images.githubusercontent.com/48481963/114770165-1c64d900-9d39-11eb-983d-88820587f7b4.png)
Alguien me lo puede explicar? 😺

**Comment by jcechavarri** [comment]
Hola!

### Duda 1
Con respecto a tu primera duda, la idea es ir desarrollando la expresión T(2^k) hasta encontrar cual es el patrón que se va repitiendo después de cada llamada recursiva. Así, llegamos a
![image](https://user-images.githubusercontent.com/42159312/114773315-e4f82b80-9d3c-11eb-84e1-e6149fb53354.png)
Después, queremos ver cuando se cumple el caso base (fin de la recursión). Esto se da cuando i=k, dónde se cumple que
![image](https://user-images.githubusercontent.com/42159312/114773494-238de600-9d3d-11eb-882b-8462a8a20842.png)
ya que T(1) = 1 (lo definimos antes). Finalmente la expresión que define a T(n) <= T(2^k) es 
![image](https://user-images.githubusercontent.com/42159312/114774042-c6466480-9d3d-11eb-836d-00288f7c8c27.png)



### Duda 2
Para tu segunda duda, recuerda que se define
![image](https://user-images.githubusercontent.com/42159312/114774298-0ad20000-9d3e-11eb-82c9-188938b63e0e.png)
Entonces, cuando tenemos la ecuación
![image](https://user-images.githubusercontent.com/42159312/114774447-3359fa00-9d3e-11eb-9ff7-e287f6bd5e3f.png)
pero queremos volver a escribirla en función de n y no podemos usar la ecuación n = 2^k para despejar k ya quen puede ser menor a 2^k. Entonces, por la primera definición, sabemos que 2^k <= 2n. Así, podemos reemplazar la ecuación con k = log(2n)   y obtener la complejidad.

Cualquier duda que te haya quedado escribe nomas!

**Comment by beatrizacuna** [comment]
Aaaaah sii muchas gracias 😸  todo claro!!
