### ISSUE TITLE
[Tarea 1] Problema instalando libpng en mac

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2133-PUC/2021-1#103]
Hola, estoy tratando de instalar `libpng-dev` con el comando que entregaron en el repositorio de la tarea, pero tengo el siguiente error:

![Captura de Pantalla 2021-04-14 a la(s) 9 46 14 p  m](https://user-images.githubusercontent.com/53795716/114801982-d7f23100-9d6a-11eb-9452-7602b369f4c4.png)

(Estoy en Big Sur)

He buscado harto para ver que pasa pero no he encontrado nada, aunque encontré otra forma de instalar `libpng` en [esta página](http://macappstore.org/libpng/) pero no sé si es la misma versión que se pide que instalemos.

Saludos!

**Comment by lucas-valenzuela** [comment]
Para mac, recomiendo usar homebrew, corriendo el comando `brew install libpng`. 

Si no tienes homebrew lo puedes instalasr según las indicaciones de su  [página oficial](https://brew.sh/index_es). Homebrew es lejos de las cosas más útiles que tiene mac, si o si te va a servir para instalar otras cosas en tus próximos ramos.

Saludos

**Comment by benjaminlillo** [comment]
Ok, gracias!

**Comment by cpgarrido** [comment]
Hola, instalé libpng con brew, pero al hacer make me sigue tirando error en  #include <png.h>, que no existe. Debo instalarlo de todas maneras con sudo o qué debo hacer?

**Comment by maureencooper** [comment]
Hola!! @cpgarrido me pasa lo mismo! Como lo solucionaste?

**Comment by cpgarrido** [comment]
@maureencooper probé de muchas formas y la única solución fue descargar la máquina virtual, que tampoco me había funcionado la que habían sugerido, pero la solución es buscar alguna máquina virtual que sea específicamente para tu computador. En mi caso, tengo chip M1, por lo que nos servían las mismas, descargué una que se llama Parallels.

**Comment by maureencooper** [comment]
@cpgarrido buenaaa también tengo M1!! Te pasaste muchísimas gracias!!
