### ISSUE TITLE
[Tarea 1] Duda sobre qué archivos se pueden modificar

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2133-PUC/2021-1#104]
Hola, no me quedó claro qué archivos tenemos que crear/modificar. ¿Se pueden modificar los archivos de `image` que vienen en el código base? En `main.c`, ¿Se puede escribir código fuera de las zonas donde se pide que se implementen funcionalidades? ¿Y podemos crear todos los archivos o structs que consideremos necesarios?

Saludos!

**Comment by nmcin** [comment]
Hola,

Eres libre de crear/modificar todo lo que quieras mientras puedas generar el output requerido. Sin embargo, te recomendamos no modificar el codigo de la carpeta `image`.

**Comment by benjaminlillo** [comment]
Ok, gracias!
