### ISSUE TITLE
[Tarea 1] make me genera un "undefined reference to" al compilar

### ISSUE THREAD

**Issue by Tvergara** [IIC2133-PUC/2021-1#105]
Hola, cuando ejecuto ```make```, me da el error "/home/tom/desktop/IIC2133/T1-2021-1-Tvergara/src/filters/main.c:21: undefined reference to `image_to_tree'". No se porque sucede, alguien me podría guiar en qué debo revisar para arreglarlo? Tengo el código subido a mi repo de la tarea.

**Comment by nmcin** [comment]
Hola,

No te complia es porque estas usando la carpeta `structs`, la cual no está especificada en la **Makefile**. Puedes agregarla a la lista de carpetas que la **Makefile** compila, especificándola en la variable `COMMON`.

**Makefile**:
```
[...]

# Directorios con elementos de uso común
COMMON=imagelib structs

[...]
```

**Comment by Tvergara** [comment]
Buenísimo! Ahí funcionó
