### ISSUE TITLE
[Tarea 1] Area Filter

### ISSUE THREAD

**Issue by Pedrowach** [IIC2133-PUC/2021-1#107]
Hola! Me surgió una duda con Area Filter, que pasa si partimos en el vecindario que no tiene nodo padre ( caso nodo raíz) y además este no cumple con alguna de las condiciones. Sus pixeles tomarían el valor del umbral del nodo menos 1 (a menos que el nodo sea de umbral = 0) ???

**Comment by nmcin** [comment]
Hola,

El "caso base" si no se cumplen las condiciones es dejar de color negro.
