### ISSUE TITLE
[Tarea 1] Qué pixeles cambiar en Area Filter

### ISSUE THREAD

**Issue by FloValdes** [IIC2133-PUC/2021-1#108]
Hola, estoy un poco confundida con el tema de los vecindarios y los pixeles a cambiar o mantener en Area Filter. Con la descripción y el ejemplo, entiendo que para calcular las condiciones se toma en cuenta el vecindario (es decir los pixeles conectados con color >= U, es decir el nodo padre en el que esté y sus hijos), pero al momento de cambiar pixeles de color o de mantenerlos, parece que solo aplica a los más oscuros (lo que sería solo los pixeles del nodo padre) en el ejemplo, pero en la descripción del filtro solo se dice los pixeles, como si fueran todos los del vecindario.

Relacionado a lo anterior, en el ejemplo, ¿qué pasaría en este segundo paso si G hubiese sido igual a 2?

![image](https://user-images.githubusercontent.com/37163115/115127725-c39a7800-9fa6-11eb-8bce-9763afab5268.png)

Siguiendo lo de cambiar solo los más oscuros, pensaría que los pixeles 8, 13, 14, 18 y 19 pasan a tener el valor 0. En un paso posterior, los pixeles 7, 12 y 17 se mantienen con color 3 pero el 9 también pasa a 0. ¿Eso es correcto?

Gracias!

**Comment by TrinidadVargas** [comment]
Hola, cuando un nodo de pixeles no cumple la condición, pasan al color final del nodo padre (0 si es el nodo raíz)  
En el ejemplo, hay un nodo gris (2) {8, 13, 14, 18, 19} que tiene dos nodos hijos blancos (3) {7, 12, 17} y {9}. 
El nodo {8, 13, 14, 18, 19} tiene area = 9 (incluye sus nodos hijos) y gris = 2 por lo que cumple ambas condiciones. 
Luego, el nodo {9} no cumple la condición de área por lo que su color es el de su padre (2) 
Por último, el nodo {7, 12, 17} cumple las dos condiciones A= 3 y G = 3 por lo que es blanco (3)

Por otro lado, el nodo {1-6, 10, 11, 15, 16, 20, 22-24} no cumple la condición de gris por lo que su color es negro. Y los nodos {21} y {25} no cumplen la condición de área por lo que su color es el de sus padre (0)

**Comment by FloValdes** [comment]
Hola, creo que entiendo mejor, gracias, pero por qué el nodo gris 8 13 14 18 19 cumpliría la condición si es que G=2? la condición no es que su valor de gris sea estrictamente mayor? entonces como su valor es igual a 2, no la cumple.

**Comment by TrinidadVargas** [comment]
el ejemplo está con G = 1 por lo que el nodo {8, 13, 14, 18, 19} si cumple la condición de G > 1

**Comment by FloValdes** [comment]
Sí, pero pregunto qué pasaría con G=2 porque ese caso no me queda tan claro qué hacer

**Comment by Brocoleta** [comment]
Hola que pasa si el nodo root tiene G=2 y no cumple alguna condicion? este pasaria a ser G=1 o G=0?
