### ISSUE TITLE
[Tarea1] Aclaración enunciado

### ISSUE THREAD

**Issue by Aloncarrasco** [IIC2133-PUC/2021-1#109]
Para ambos filtros, en el caso de que el **PRIMER NODO** del árbol **NO** cumpla las condiciones de los filtros y que sus pixeles **NO** sean negros, el color asociado a este nodo será negro. Así por ejemplo, si un hijo de este nodo no cumple con la condición del filtro se deberá colorear con negro también (pues su padre, el nodo base, es negro).

**Comment by perezpefaur** [comment]
Como el segundo filtro no va a cumplir las condiciones del filtro? Si es que siempre va a ser cero ya que no tiene padre

**Comment by nmcin** [comment]
Para el nodo raíz en el filtro delta, al no tener padre no se puede calcular su variación, pero no es que sea cero. En ese caso, debes pintar el nodo con negro.
