### ISSUE TITLE
[Tarea 0] re-modelar funciones person.py

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2133-PUC/2021-1#11]
Hola, dentro de las funciones que tenemos que remodelar, me surgio una duda en recursive_inform dentro del archivo person.py. 
no me queda claro que tipo de parametro es output_file, para poder definirlo de manera correcta en mi archivo en c.

**Comment by TrinidadVargas** [comment]
Hola! 
```output_file``` es un archivo de texto en Python y ```FILE *```en C
Efectivamente hay un error en la base de Python que dice ```int``` en la función ```recursive_inform``` de World pero esto no afecta el programa en si.

**Comment by Huasito-Appel** [comment]
osea dentro de mi funcion tengo que declararlo como un puntero? eso no me quedo muy claro

**Comment by TrinidadVargas** [comment]
Si, en C los archivos se trabajan con punteros, es una dirección que indica a partir de donde se debe escribir o leer un string.
