### ISSUE TITLE
[Tarea 1] Duda max tree

### ISSUE THREAD

**Issue by Brocoleta** [IIC2133-PUC/2021-1#110]
Hola, se puede implementar el max tree de forma que cada nodo tenga una conexión con los nodos de su mismo nivel y no solo con sus padre e hijos,  o esto iría en contra de la definición de la estructura?

**Comment by nmcin** [comment]
Hola,

Puedes implementar como quieras mientra que logres el output correcto en el tiempo máximo, sin embargo, lo que tu propones probabablemente te genere mucha complejidad adicional y no le veo ningún claro beneficio.

Perdón por contestar tan tarde, saludos!
