### ISSUE TITLE
[Tarea 1] Segmentation Fault: 11 con código base

### ISSUE THREAD

**Issue by FdoTorres1** [IIC2133-PUC/2021-1#112]
Hola!

Hice clone del repositorio de la tarea 0 y compilé el código sin haber cambiado nada. Procedí a correrlo dando como input `test_1` y me arrojó `Segmentation Fault: 11` sin imprimir nada en consola ni generar output. Es algún error que no estoy viendo o es normal que arroje ese error con el código base (supongo que por la falta de implementar algo). En caso de que no debiese ser así, agradecería si me pudieran ayudar a solucionarlo.

**Comment by nmcin** [comment]
Hola,

El input que le entregas debe corresponder a una imagen PNG que exista en la ruta que indicas de input. Recuerda que también debes incluir la extensión del archivo (`.png`).

**Comment by FdoTorres1** [comment]
Creo haber tomado en cuenta esas cosas, pero nosé si de la forma correcta, feliz si me pudieras ayudar a ver el error.
