### ISSUE TITLE
Duda de un nodo del  Max Tree en enunciado

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#113]
Hola, tengo una duda sobre el ejemplo que sale en el anunciado del Max Tree
![image](https://user-images.githubusercontent.com/59337116/115242820-424efc80-a0f0-11eb-9a16-a1b522474367.png)
Por qué el 7 y el 9 son dos nodos distintos y no sólo uno que contenga a ambos?
Gracias!

**Comment by JuanDlugo** [comment]
Hola! no soy ayudante, pero lo que yo entiendo es que se separa todo por "vecindarios" o áreas de pixeles que estén juntos. En este caso como el pixel 7 y el 9 no están conectados entre sí, pertenecen a vecindarios distintos si bien son de la misma intensidad. Espero te sirva! :D

**Comment by lucas-valenzuela** [comment]
Esto mismo, 7 y 9 son vecindarios independientes
