### ISSUE TITLE
Outputs T1

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#114]
Hola, si bien una imagen puede ser testeada con distintos filtros y parámetros, cómo sabremos si con el test de imágenes que nos están dando vamos a entregar un output correcto? Pueden subir un ejemplo de output para un test de imagen en particular?

**Comment by JuanDlugo** [comment]
Sii estaría muy útil!

**Comment by nmcin** [comment]
Lo tenemos en consideración.
