### ISSUE TITLE
[Tarea 1] Uso de hash table

### ISSUE THREAD

**Issue by Brocoleta** [IIC2133-PUC/2021-1#115]
Hola, es legal una vez ya armado el árbol con sus nodos, ocupar una hash table para acelerar procesos de búsqueda?

**Comment by nmcin** [comment]
Hola,

Si es _legal_ lo que propones y un buen ejercicio para entender como funcionan las tablas de hash, aunque debes saber que la estructura de árbol también permite aplicar los filtros que les pedimos de manera muy eficiente. Si lo quieres hacer con tablas de hash, estas en tu derecho _legal_, pero te recomiendo al menos probar implementar los filtros con la estructura de arbol.
