### ISSUE TITLE
Area filter

### ISSUE THREAD

**Issue by perezpefaur** [IIC2133-PUC/2021-1#117]
Tenemos que asumir siempre que en una imagen existe un pixel de grisaceo 0 (color negro)? Si no es asi, que pasa si un pixel no tiene padre pero no es de grisaceo 0, sino por ejemplo 1. Tambien se mantendria su grisaceo o se cambia a un grisaceo 0.

Me pregunta nace por esto del enunciado: 
 En cambio, si un vecindario no cumple con alguna condici´on, los p´ıxeles pasan a tener el tono de gris que tiene su padre
en ese momento. Si dicho p´ıxel es negro, se mantiene en cero su gris´aceo.

**Comment by nmcin** [comment]
En ese caso píntalo negro.
