### ISSUE TITLE
[Tarea 1] Tiempo de ejecución imagenes pesadas.

### ISSUE THREAD

**Issue by jtcaraball** [IIC2133-PUC/2021-1#118]
Hola! Veo que en el enunsiado se pide que cada caso se ejecute en menos de 10 segundos, sin embargo, no consigo hacer que procesar la foto y reescribirla a formato png, sin aplicar filtros, tome menos de 30 segundos para el caso de la imagen hard/campus.png (En particular creo que es muy costoso generar los vecindarios ).  Solo quiero confirmar el tiempo de ejecución máximo antes de partir denuevo y replantear la implementación 😢

Saludos!!

**Comment by CarloGauss33** [comment]
El tiempo máximo de ejecución tal como dice el enunciado es de 10 segundos. 

Aunque, si utilizas _wsl2_ puede ser que tus tiempos de ejecución estén siendo afectados por el acceso a archivos. Esto se puede observar cuando el tiempo _real_ de time tiene mucha diferencia con el _user+sys_ (en general no son nunca iguales, pero es buen indicador para saber donde estan los errores)
Si este es tu caso, te recomiendo probar lo siguiente

```sh
cp nombre_ejecutable ~/tarea0/nombre_ejecutable
cp test_X.txt ~/tarea0/test_X.txt
cd ~/tarea0/
```
Luego utilizas el comando para ejecutar tu tarea

Con eso copiaras tu ejecutable y un test a la carpeta _home_ de tu distribución de Linux, de esta forma los tiempos de acceso a los archivos disminuye (de tener que solicitar recursos compartidos a Windows). Lo que debería provocar una disminución en el tiempo _real_ de ejecución
