### ISSUE TITLE
[Tarea 1] Problema instalando libpng

### ISSUE THREAD

**Issue by Benjale** [IIC2133-PUC/2021-1#119]
Hola, estoy tratando de instalar libpng-dev  hace días con el comando que entregaron en el repositorio de la tarea, pero tengo el siguiente error:

![image](https://user-images.githubusercontent.com/62115136/115564573-925fc780-a286-11eb-9057-0ac8f4ec3be5.png)

He buscado harto para ver que pasa pero no he encontrado nada
Saludos

**Comment by nmcin** [comment]
Hola,

Prueba ejecutando `sudo apt update` y luego `sudo apt install libpng-dev`.
