### ISSUE TITLE
[Tarea 0] Dudas sobre traspasar modelación python

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2133-PUC/2021-1#12]
1) ¿Está permitido implementar el problema como queramos o es necesario 'traspasar' el código de python a C?

2) En el código que subieron de python hay eventos sin implementar como STATISTICS y POSITIVE. No hay nada que los referencie en Word.py ni en Person.py, y en main.py se deja un pass.

**Comment by agustin-rios** [comment]
1.  Puedes hacer cualquiera de los dos, pero por experiencia propia recomiendo el 'traspasar' (te complicaras menos).
2. Son funciones que ustedes deben implementar desde 0, por lo que ese pass esta bien.

**Comment by nhorellana** [comment]
> 2. Son funciones que ustedes deben implementar desde 0, por lo que ese pass esta bien.

Hola! Hay que implementarlas en en python y en C o solo en C?

**Comment by rbhernandez** [comment]
Hola @nhorellana! solo debes implementarlo en **C**, lo que será evaluado es el código en ese lenguaje. El código de python es entregado para aprender a usar C a partir de la comparación con un lenguaje conocido, por lo que una vez que lograste "traspasar" las funciones que están detalladas en el archivo de python se espera que te hayas familiarizado y puedas escribir en C las funciones que vienen con un _pass_.

Saludos!
