### ISSUE TITLE
[Tarea 1] Duda nodo raiz

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2133-PUC/2021-1#120]
El nodo raiz de nuestro max-tree siempre debe ser todos los pixeles que tienen el mismo umbral siendo este umbral el mas pequeño de la imagen?

**Comment by FdoTorres1** [comment]
No soy ayudante, pero tengo entendido que el nodo raíz contiene a todos los píxeles que tienen un umbral igual al más bajo de la imagen.
