### ISSUE TITLE
[T1] Situacion multipadres

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#121]
Hola,
Se me surgio una duda sobre que hacer en situacion de multipadres para un vecindario:
![image](https://user-images.githubusercontent.com/69604944/115634562-d6c78380-a2d7-11eb-9866-fcbca2632df9.png)
En este caso cual seria el padre de la zona blanca?

**Comment by Huasito-Appel** [comment]
+1  a la consulta.

**Comment by Aloncarrasco** [comment]
Hola, hice una pequeña capsula para explicar un poco mejor el árbol y que incluye un caso muy parecido a ese, avísame si te ayuda.
https://youtu.be/QSixrlGHDDo

**Comment by rgmorales1** [comment]
@Aloncarrasco una consulta, ya que el enunciado dice consideremos que cada pixel solo tiene 4 vecinos como máximo (arriba, abajo, izquierda y derecha), me queda una confusión en el siguiente ejemplo:
![WhatsApp Image 2021-04-21 at 11 43 20 PM](https://user-images.githubusercontent.com/53887061/115652737-ccb77c00-a2fb-11eb-9231-9d52237b7c69.jpeg)

Específicamente en este nodo:

![WhatsApp Image 2021-04-21 at 11 44 25 PM](https://user-images.githubusercontent.com/53887061/115652821-f96b9380-a2fb-11eb-80f7-b5c2af0fa7c9.jpeg)

En este caso, ¿no se debería separar el nodo |3 8 11 12 14 15 18 23| en los siguientes 4 nodos |3 8| , |11 12| , |14 15| y |18 23|? En el caso de ser así ¿los 4 nodos compartirían el mismo vecindario? La duda me surge por que los pixeles del mismo umbral en el ejemplo están en diagonal. 

Y además en el ejemplo del enunciado, el pixel 25 que posee el umbral gris, lo separan de los demás por estar en diagonal. 
![image](https://user-images.githubusercontent.com/53887061/115653272-dab9cc80-a2fc-11eb-8a78-6361c3215182.png)

**Comment by Aloncarrasco** [comment]
Hola, lo explique en el video. la cruz entera es UN VECINDARIO (como la casilla 13 es más clara que el gris entonces pertenece al vecindario) y este vecindario se la asigna al 2do nodo y este nodo solo guarda los pixeles del vecindario que tienen un color igual umbral. 

Te recomiendo ver el video de nuevo y prestarle atención porque ahí explico como se arma ese nodo.
