### ISSUE TITLE
[Tarea 1] area filter

### ISSUE THREAD

**Issue by Afro27** [IIC2133-PUC/2021-1#122]
Cuando en el enunciado dice que si no se cumplen las condiciones, el pixel debe cambiarse al grisáceo de su nodo padre en ese momento. "Ese momento" es el grisáceo que tenia la imagen inicial o si lo cambié antes debe ser ese nuevo color. De ser al nuevo color, estamos obligados a aplicar el filtro desde la raíz hacia abajo? Ya que si lo aplicamos recursivamente desde abajo hacia la raíz el resultado sería distinto. Gracias.

**Comment by nmcin** [comment]
Hola,

Efectivamente se refirere al nuevo color y efectivamente deben aplicar el filtro desde la raíz hacia las hojas.
