### ISSUE TITLE
[T1] Segmentation fault al guardar .png

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2133-PUC/2021-1#123]
Hola! desarrollando mi tarea, me di cuenta que al momento de llamar a `img_png_write_to_file(new_img, argv[2]);`, el programa me arroja `Segmentation fault (core dumped)`. No entiendo a que se debe, porque _literalmente_ no he tocado la **new_img**. Si comento la línea, luego el programa alcanza a imprimir `Listo!`, pero luego se cae en la línea de `img_png_destroy(image);`, con el mismo error. Si comento **ambas** líneas, el programa funciona correctamente, pero claramente no se libera memoria ni se guarda el png. Alguna idea?
Gracias!

edit: si comento toda la creación del árbol, el error ya no sale. Pero hago énfasis que nunca toqué el **new_img**, por lo que no entiendo que tiene que ver mi árbol con eso si nunca lo edité.

**Comment by nmcin** [comment]
Hola,

Al correrlo con valgrind, que error te da?

**Comment by Christian-Klempau** [comment]
Hola! ya me ayudaron a resolverlo! valgrind me sirvió
Gracias :D
