### ISSUE TITLE
Duda Area Filter

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2133-PUC/2021-1#125]
Hola. Tengo una duda de como funciona el área filtre. Si es que un vecindario no cumple con ambas condiciones, eso significa que no debería seguir analizando en las ramas de dicho vecindario? Ya que todos los nodos habrían cambiado de color al mismo. O solo cambian de color los pixeles propios del nodo y no todos los del vecindario para abajo?

**Comment by nmcin** [comment]
Hola,

Eso esta repondido al final de la issue #98 con una breve explicación, sin embargo, la respuesta es que sí debes seguir analizando las ramas.
