### ISSUE TITLE
Duda Filtros

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2133-PUC/2021-1#127]
Al aplicar los filtros solo deben cambiar de color los pixeles propios del nodo? O todos los del vecindario asociados a ese nodo? Además, en el caso del delta filter, cuando en el enunciado dice que no existe variación con respecto a su padre, se refiere al color?

**Comment by lucas-valenzuela** [comment]
Hola,

> Al aplicar los filtros solo deben cambiar de color los pixeles propios del nodo? O todos los del vecindario asociados a ese nodo? 

Depende. Recuerda que el filtro se va aplicando iterativamente a los nodos, por lo que puede ser que para un nodo x se mantengan los colores originales de los píxeles de su vecindario, pero perfectamente puede suceder que  un nieto del nodo x no cumpla con las condiciones, por lo que todos los píxeles asociados a ese nieto se 'pintan' con el padre del nieto.

> Además, en el caso del delta filter, cuando en el enunciado dice que no existe variación con respecto a su padre, se refiere al color?

Se refiere a que tanto el padre como el hijo tienen la misma cantidad de píxeles, por lo que no hay variación.
