### ISSUE TITLE
[Tarea 0] Duda formato de input en RECOVERED

### ISSUE THREAD

**Issue by Tvergara** [IIC2133-PUC/2021-1#13]
Hola, me pareció extraño que en el enunciado digan que en el comando RECOVERED no se entrega el depth. En el main.c entregado suponen como que sí lo entregan al obtener este comando, y en el  test_5.txt me parece que efectivamente lo entregan antes del route. Es posible que sea un error en el enunciado y sí se encuentre entregado como parte del input?

**Comment by nmcin** [comment]
Hola,

En el enunciado aparece que un evento RECOVERED se entrega en el siguiente formato:
```RECOVERED country region person_route ```. Dentro de `person_route` el primer número corresponde a la profundidad y luego esta el camino para llegar a la persona indicada. El detalle de `person_route` está especificado justo antes de los eventos, en el enunciado.

**Comment by Tvergara** [comment]
Muchas gracias!
