### ISSUE TITLE
Delta filter caso inicial

### ISSUE THREAD

**Issue by perezpefaur** [IIC2133-PUC/2021-1#132]
1. Con U >= 1, es el caso inicial, por lo que por defecto parte se le asociará con el tono negro. Esto servirá en los próximos casos, particularmente con los hijos que no cumplan con el filtro y se deben colorear como su padre (con negro en este caso).

_Originally posted by @lucas-valenzuela in https://github.com/IIC2133-PUC/2021-1/issues/98#issuecomment-820653443_

No tiene sentido el enunciado entonces si dice: Como no hay ning´un p´ıxel con U = 0, el nodo ra´ız se inicia con U ≥ 1. Con U ≥ 1, el vecindario contiene 25 p´ıxeles. Como no hay variaci´on no el anterior, no se aplica el filtro puesto que el nodo ra´ız no tiene padre.

Pero aun asi en la imagen se cambia el color a 0 y se le aplica el filtro al primer nodo.

**Comment by lucas-valenzuela** [comment]
Hola!

Efectivamente ese caso puede llevar a una contradicción. Específicamente para el segundo filtro, considera lo que se explica en el enunciado en  la parte del filtro, no te guíes por la regla general.
