### ISSUE TITLE
Tamaño input

### ISSUE THREAD

**Issue by VicenteElCyrano** [IIC2133-PUC/2021-1#133]
Las imágenes vienen con un tamaño dado por su ancho y altura, podemos asumir que los nunca el ancho y/o la altura de la imagen serán igual a 1?

**Comment by lucas-valenzuela** [comment]
Estrictamente hablando, una imagen de 1x1 también sería un caso válido. Sería simplemente un árbol formado por un nodo. Ahora bien, puedes asumir que no habrán tests de este estilo, pues no tiene mucho sentido utilizar un max-tree para una configuración de ese estilo.
