### ISSUE TITLE
Duda al seleccionar vecindarios de un nodo

### ISSUE THREAD

**Issue by aljara97** [IIC2133-PUC/2021-1#134]
Hola, al revisar el enunciado aún no puedo entender en parte cómo se selecciona un vecindario completo que ocupa un nodo. Según lo que tengo entendido un vecindario une a todos los pixeles que tienen una relación de vecino con al menos otro pixel del vecindario. Pero en el ejemplo que se presenta, en específico para el nodo padre, no me queda claro por qué se considera que los pixeles 22, 23 y 24 son parte del vecindario del nodo padre, ya que, ninguno se estos se encuentra arriba, abajo, o a los lados de los pixeles 16 y 20.
![imagen](https://user-images.githubusercontent.com/42227563/115944642-f223c180-a484-11eb-9049-1709f35df8e6.png)
Lamento si mi pregunta es un poco obvia, pero no me queda claro cómo se definió este vecindario o si es que se decidió incluirlos en el mismo nodo siendo vecindarios independientes que cumplían la restricción del umbral.

De antemano muchas gracias :)

**Comment by matipina** [comment]
No soy ayudante, pero creo que el enunciado dice que un vecindario está conformado por todos los pixeles que tienen valor **mayor** o igual al umbral, es decir, en el ejemplo **todos** los píxeles corresponderían al vecindario del nodo raíz, pero solo se almacenan en este nodo los que tienen valor igual al umbral, el resto se van almacenando en los nodos hijo. 

Al menos eso entendí yo, si después algún ayudante puede confirmarlo estaría bacán :)

**Comment by lucas-valenzuela** [comment]
Precisamente es lo que dice @matipina. En el caso del nodo padre, todos los pixeles son parte del vecindario porque obviamente todos los píxeles cumplen con ser mayores o iguales al color mínimo (negro). Además, es claro también que es una región contigua, por lo que los 25 píxeles forman parte del vecindario. Ahora bien, recuerda que solamente los píxeles iguales al umbral son guardador por el nodo padre.

**Comment by aljara97** [comment]
Bacán, muchas gracias a los dos, ahora me queda mucho más claro :D
