### ISSUE TITLE
[Tarea 1] Duda Informe Parte de Complejidades

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2133-PUC/2021-1#135]
Hola!
Mi duda es si el cálculo de las complejidades que hay que hacer en el informe son las complejidades de la estructura de árbol que implementamos en nuestra tarea, o si además hay que calcular las complejidades si lo hicieramos con un Component Tree.

**Comment by lucas-valenzuela** [comment]
El enunciado solo pide las complejidades de la implementación del Max-Tree y de los filtros. Ahora bien, para la parte de comparar al Component Tree con el Max Tree, quizás podría serte de ayuda analizar si varían las complejidades teóricas según cada tipo de árbol.
