### ISSUE TITLE
[Tarea 1] Filtro Delta Nodos Vecindario

### ISSUE THREAD

**Issue by ignacio-urrutia** [IIC2133-PUC/2021-1#137]
Hola! Tengo una duda con respecto al filtro Delta. En la fórmula para calcular D se habla del número de pixeles del vecindario del nodo padre, sin embargo, a medida que el filtro va corriendo, cuando un nodo no cumple las condiciones del filtro, este pasa a ser del color del padre. Mi duda es, este nodo, al ser del color del padre, se considera el mismo nodo que el nodo padre? Y por lo tanto, sus hijos deben considerar el número de nodos de este después de haber aplicado el filtro sobre este y haberse "fusionado con el nodo padre"? Espero que se entienda la duda. Gracias!4

**Comment by nmcin** [comment]
Hola,

Los pixeles que cambian de color al aplicar el filtro no deben ir reajustando su posición en el arbol, no hay que fusionar los nodos.
