### ISSUE TITLE
[TAREA 0] Duda en main.c

### ISSUE THREAD

**Issue by isiguelfand** [IIC2133-PUC/2021-1#14]
Hola! Quería saber si los "[por implementar]" en el main deben seguir el orden en el que están. No entiendo como se generaría una "matriz" como describe el enunciado al bosque sin saber el tamaño de los arreglos que la componen.  En la línea 52 dice que se debe generar el mundo antes de saber cuantas regiones hay. 
Muchas gracias!!

**Comment by nmcin** [comment]
Hola,
No es obligación que sigas el mismo orden, pero si te lo recomendamos. Puedes crear un arreglo de punteros, y una vez que sepas el tamaño de cada país, creas el espacio en memoria para el arreglo de regiones del país (con `calloc` o `malloc`) y lo guardas dentro del arreglo de países.

**Comment by isiguelfand** [comment]
Gracias!
