### ISSUE TITLE
comando de ejecución 

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#140]
Hola no entiendo bien el comando de ejecución de la tarea: `./filter <input.png> <output.png> <filtro> <d/A> <G>`
por qué "./filter" ?
en qué carpeta debo estar?
he intentado correr lo siguiente:
![image](https://user-images.githubusercontent.com/59337116/116113532-9032aa00-a686-11eb-8f49-5dd0710e9479.png)
![image](https://user-images.githubusercontent.com/59337116/116113802-d851cc80-a686-11eb-82be-6f9170252491.png)

no entiendo en qué me estoy equivocando... si me pudieran ayudar por favor ..

**Comment by nmcin** [comment]
Hola,

Al compilar con `make` en la carpeta raíz (la que continene a src y la Makefile) se debe crear un ejecutable llamado `filters` dentro de esa misma carpeta. Ese ejecutable lo puedes correr con `./filters <input.png> <output.png> <filtro> <d/A> <G>`, desde la misma carpeta raíz, donde   `<d/A>` se refiere al parámetro Delta o Area (no es que vayan separados por un "/", hay un par de ejemplos en el README) y `<G>` el valor de gricaseo para el filtro area (no se pone nada para el delta).

Te recomiendo además dejar los tests en una carpeta separada del código.

```
(raiz)
  |------ src
  |        |-----filters
  |        |          |-----main.c
  |        |          |-----archivos.c
  |        |          |-----archivos.h
  |        |
  |        |-----imagelib
  |        |          |----- (...)
  |         
  |------ tests
  |        |-----(...)
  |
  |------ Makefile
  |------ filters   (compilado con make)
```

Bajo esa estructura puedes ejecutar desde la raíz:
`./filters tests/easy/test_1.png out.png area 10 30`
o
`./filters tests/easy/test_1.png out.png delta 0.1`

**Comment by Camila-sty** [comment]
gracias
