### ISSUE TITLE
[Duda C] Eliminar primer elemento de array.

### ISSUE THREAD

**Issue by PDominguezW** [IIC2133-PUC/2021-1#144]
En mi programa tengo un algoritmo DFS y para hacer el stack tengo un array. Cuando quiero eliminar el primer elemento del array, muevo todos los elementos que ya estaban en el array, una posición a la izquierda, lo que he notado que tiene un alto costo en términos de tiempo de ejecución. Hay alguna manera mas eficiente de hacer esto? Intente liberando el primer espacio de memoria y cambiar el puntero del array al segundo elemento, pero me mandaba un error al implementar este método.

**Comment by nmcin** [comment]
Hola,

¿Quieres hacer un stack o una cola FIFO?
Porque para hacer un stack puedes ir guardando en un int la posición del ultimo elemento del stack, al agregar un elemento incrementar la posición y agregarlo al arreglo, y al eliminar simplemente leer la posición en el arreglo y decrementar la posición.

También puedes usar una lista ligada si no quieres definir el largo del arreglo de antemano.
