### ISSUE TITLE
Problemas al guardar la imagen.

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2133-PUC/2021-1#145]
Hola! Estaba intentando guardar la imagen con el comando "img_png_write_to_file" y me tira un error extraño.
Primero me asegure de que el formato de new_img sea igual que el recibido en image, y efectivamente son iguales (printie todos sus atributos).
Luego al correr con valgrind me tira el siguiente error:
 
![Captura de Pantalla 2021-04-27 a la(s) 11 01 47](https://user-images.githubusercontent.com/48494298/116265381-1283a280-a749-11eb-9fd5-86bdc5b3fa61.png)

Lo que señala que el programa se cae en la linea 100 del image.c que corresponde a:

![Captura de Pantalla 2021-04-27 a la(s) 11 06 15](https://user-images.githubusercontent.com/48494298/116265491-2929f980-a749-11eb-86ff-b6a51e01083b.png)

Lo que me parece extraño porque sería algo como que se esté leyendo mal el archivo con el write bytes. 
Porfavor si me pueden guiar por donde mas o menos podría estar el error.
Gracias! :D

**Comment by nmcin** [comment]
Hola,

¿Qué argumento estas usando de output?
Es importante que exista la carpeta donde se guardará la imagen de output.
Por ejemplo, si le das como argumento de output `out/easy/1.png`, debe existir la ruta `out/easy/`.

**Comment by JuanDlugo** [comment]
Le entregue el siguiente comando "valgrind ./filters tests/easy/test_1.png output.png area 5 60" 
Y en mi carpeta inicial coloque una imagen.png llamada output.png de la siguiente manera:
<img width="211" alt="Captura de Pantalla 2021-04-27 a la(s) 12 09 52" src="https://user-images.githubusercontent.com/48494298/116275621-cdb03980-a751-11eb-9624-4ceae355444e.png">

generaría esto algún conflicto?

**Comment by nmcin** [comment]
Eso no debiera ser problemático, veamos tu caso en Discord.

**Comment by JuanDlugo** [comment]
Dale perfecto, a qué hora estarás disponible?
y gracias de antemano!

**Comment by nmcin** [comment]
Ahora

**Comment by JuanDlugo** [comment]
Por si alguien llega a tener el mismo problema, era que mi usuario de mi maquina virtual no tenia el acceso permitido para crear los .png
Asi que se soluciona con correr el mismo comando de valgrind pero con "sudo" antes.
:)
