### ISSUE TITLE
[Tarea 1] Función que escribe output no escribe la misma foto al pasarle la imagen de input

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2133-PUC/2021-1#146]
Hola, he estado un buen rato debugueando y no he encontrado un solo error. Sin embargo, utilizando varios softwares (diff, imagemagick, otros online) me arrojaban diferencias.

Finalmente, testee ```img_png_write_to_file(image, argv[2]);``` y el resultado me continúa arrojando diferencias (no modifique ese módulo). Tengo la librería necesaria instalada y estoy usando Xubuntu 20.04 para ejecutar mi tarea.

Al parecer las versiones de la librería que tengo instaladas son: Multiple-image Network Graphics (libpng 1.6.37) Portable Network Graphics (libpng 1.6.37)

Edit: logré trabajar a ciegas (que creo que es un poco lo complejo de esta tarea) y pude obtener buenos resultados. Los inputs no son generados igual que los output por lo que no se pueden comparar. Saludos.

**Comment by nmcin** [comment]
Hola,

No entendí tu edit pero es parte del comportamiento esperado que puedan haber diferencias al abrir y escribir la misma imagen con las funciones que les entregamos. Esto pasa porque al leer la imagen, esta se reduce desde un archivo png que puede ser a color o en escala de grises de 8 bits (gris de 0 a 255), a una imagen de 7bits (gris de 0 a 127), por lo que hay una perdida de información al abrir la imagen, la que no se puede recuperar al guardarla nuevamente.

**Comment by fmitjans** [comment]
Entonces como van a revisar nuestros outputs? Al ojo?

**Comment by nmcin** [comment]
Hola,

La imagen de input siempre se lee como la misma matriz en el programa y al exportar dos matrices iguales siempre se produce la misma imagen.
