### ISSUE TITLE
[Tarea 1] Sobre las complejidades en el informe

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2133-PUC/2021-1#148]
Hola! En el segundo punto del análisis se pide calcular la complejidad de la construcción del árbol y de la implementación de cada filtro en términos de la cantidad de píxeles, digamos _n_, y la profundidad del árbol, _h_. ¿Esto se refiere a calcular una complejidad que dependa de ambas variables, por ejemplo _O(n*h)_? ¿O simplemente calcular dos complejidades para cada operación, una que dependa de _n_ y otra de _h_?

**Comment by TrinidadVargas** [comment]
Hola! Lo primero que dices, por ejemplo O(n*h) o O(n log(h)) etc

**Comment by benjaminlillo** [comment]
Ok, gracias!
