### ISSUE TITLE
[Tarea 0] Duda archivo test.txt

### ISSUE THREAD

**Issue by josefeliuf** [IIC2133-PUC/2021-1#15]
Según lo que entendí del enunciado, la segunda línea del input debería ser el número de eventos a realizar sobre el bosque, pero el archivo test.txt tiene como segunda línea un '7', y después hay solo 4 eventos. Alguien me podría aclarar esto?

Gracias!

**Comment by rbhernandez** [comment]
Hola! Efectivamente la segunda línea es el número de eventos, por lo que sí hay un error en el archivo test.txt y **debería ser un 4 en vez de un 7**. Te recomiendo cambiarlo para usarlo localmente y también usar los test que están en siding :) 

Saludos!
