### ISSUE TITLE
Nota Informe

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2133-PUC/2021-1#150]
Hola, la verdad di la cacha en el max tree y para no tener un 1 pelao queria hacer el informe, puedo tener nota en este si mi codigo no funciona?
puedo citar un paper para el analisis de complejidad?
quedo atento, un saludo.

**Comment by TrinidadVargas** [comment]
Hola! Si si puedes hacerlo. Puedes calcular la complejidad de tu código aunque este no funcione

Saludos!
