### ISSUE TITLE
[Tarea 1] Duda sobre Area filter + concepto de vecindarios (diferentes explicaciones)

### ISSUE THREAD

**Issue by ChaparoD** [IIC2133-PUC/2021-1#151]
He leído las issues anteriores y visto el video de aclaración sobre cómo considerar los vecindarios y contar sus hijos.

Sin embargo,  al cruzar la información y ver los resultados de los test sigo sin tener claro el concepto.
Con mi estructura Max tree puedo acceder a cada uno de los Vecindarios (los cuales llamé Umbral, y dentro de este umbral existen diferentes grupos de pixeles del mismo gris, con diferentes padres entre ellos) Lo anterior va en concordancia con la siguiente imagen.
![Captura de Pantalla 2021-04-28 a la(s) 10 49 52](https://user-images.githubusercontent.com/42227494/116443988-467ec680-a822-11eb-801c-6e69c9c8c62d.png)

Donde los nodos 21, 7  y 9 serían del mismo vecindario por enunciado (del mismo umbral en mi modelación), pero cada pixel (o grupo de pixeles en caso de ser más) tiene diferente padre (NOTAR QUE 7 Y 9 SE CONSIDERAN POR SEPARADOS AL NO SER VECINOS). Hasta acá todo bien. Por lo tanto , para considerar los hijos del umbral blanco, debo sumar los hijos de pixeles (o grupos) blancos. y en el caso que no se cumpla el requisito , asignarlos al color de su RESPECTIVO padre.

El problema vuelve a surgir al ver la siguiente aclaración del video.
![Captura de Pantalla 2021-04-28 a la(s) 10 41 32](https://user-images.githubusercontent.com/42227494/116444869-361b1b80-a823-11eb-9a42-03d6bd34c013.png)
 
Donde considera los nodos (3,8) (11,12) (14,15)(18,23) como un mismo vecindario (Concordante con enunciado ya que esté guarda todos los pixeles de un mismo umbral), sin embargo, cada uno de estos grupos de gris podía tener diferentes padres, no es el caso. y entiendo que por eso se consideren juntos, pero ya es diferente a como se trata el 7 y 9 en la primera foto.

El problema vuelve a repetirse en el enunciado original.
![Captura de Pantalla 2021-04-28 a la(s) 13 38 39](https://user-images.githubusercontent.com/42227494/116448506-34535700-a827-11eb-8799-9ebef38dc791.png)

Donde al contar los pixeles del U>= 3 considera un grupo de 3 y otro de 1. (bajo esta definición, personalmente decidí separar mis vecindarios bajo un mismo umbral). Pero igual puedo acceder a ellos y considerarlos como una, tal cual como define el enunciado el concepto de vecindario. Y no lo respeta en este último caso, donde queda explícito en la siguiente parte.
![Captura de Pantalla 2021-04-28 a la(s) 13 42 12](https://user-images.githubusercontent.com/42227494/116449264-fe62a280-a827-11eb-9df2-8e7dfbb34158.png)

Donde cuenta las cantidades por separado de un mismo vecindario blanco. 

1) Debo sumar por separado el area,  de diferentes grupos de  pixeles del mismo umbral?  y bajo este numero aplicar el filtro a cada grupo en específico. (en el área solo considero los hijos de los grupos de pixeles del umbral que estoy analizando)
(según enunciado entiendo que sí)
2) Debo sumar todos los pixeles que sean mayor o iguales al umbral que estoy analizando? (area de la isla) y bajo este numero aplicar el filtro Al Vecindario y/o grupos de pixeles del umbral analizado?

Me parece más acorde a lo entendido en enunciado, realizar 1). pero los resultados no me calzan.
en el test_1 area 5 60, se pintan ambos grupos de 127, pero uno no, es decir, si se aplican los filtros por separado y no a todo el Vecindario de acorde al enunciado.
![Captura de Pantalla 2021-04-28 a la(s) 14 36 47](https://user-images.githubusercontent.com/42227494/116455560-33bebe80-a82f-11eb-8fed-704d246d7686.png)
![Captura de Pantalla 2021-04-28 a la(s) 14 37 28](https://user-images.githubusercontent.com/42227494/116455640-505af680-a82f-11eb-80bd-94a195799403.png)

Tengo la estructura lista desde el sábado, y dadas las ambiguedades presentadas en el desarrollo de la Tarea, no he podido seguir avanzando.
Entiendo que puedan surgir dudas, pero me parece que las respuestas a estas deben ser claras y consistentes, dada la exigencia en la corrección.  Adjunto diagrama de mi modelo para el test_1 según lo entendido en el estudio de Maxtree y el entendimiento del problema planteado en la Tarea 1 (disculpas por la calidad).
![IMG_2139](https://user-images.githubusercontent.com/42227494/116458568-ce6ccc80-a832-11eb-8326-4464cc55dfd9.jpg)

Muchas Gracias de antemano, me parece que este problema no solo me está pasando a mí.

**Comment by jasanchez1** [comment]
Comenzaré diciendo que entiendo que cualquier error en los enunciados de la tarea o problemas de comunicación no fueron con dolo, entendemos que fue sin intención de perjudicar a los alumnos. Sin embargo, estoy de acuerdo con lo comentado en esta issue, creo que  si bien, es adecuado que la tarea incorpore investigación por parte de los alumnos, creo que es evidente que hubo dificultades generalizadas al momento de entender lo que realmente se pedía, generando hartas dificultades. 

Lo anterior, a mi gusto, queda en evidencia cuando se necesita subir un video aclarando el enunciado  y el funcionar de la estructura, que mucha gente ni siquiera ha visto aún. El problema de lo anterior es el timming, fue **muchos** días luego de lanzar el enunciado. No había muchas formas de enterarse de errores conceptuales de la implementación de la estructura sin las soluciones de las imágenes, en mi caso en particular tampoco pude obtener respuesta en el discord (Entiendo que los ayudantes pueden estar ocupados, tampoco los culpo).

Entiendo también que se intenta solucionar esto dando mas plazo y flexibilizando el puntaje (Y se agradece el reconocimiento del problema). El problema con esto, para muchos, es que estando en semanas universitarias intensas (y existiendo también quienes trabajamos en paralelo) es que uno se organiza para realizar estas entregas, y muchas veces para arreglar estos problemas en tiempo extra, se está sacrificando tiempo que estaba destinado a ser utilizado en otros ramos o compromisos, teniendo así la posibilidad de arreglar potenciales problemas en la tarea, pero sacrificando estudio o puntaje en otras entregas (de tener tiempos limitados). 

Admito que no veo una solución fácil a todo esto. Pero creo importante expresar también este punto de vista. Gracias de ante mano!

**Comment by ChaparoD** [comment]
Dibuje mal el diagrama, el 89 se cuelga del 47.
