### ISSUE TITLE
Diferencia entre fotos

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2133-PUC/2021-1#152]
Hola estoy comparando mis imágenes de output con las soluciones y tengo pequeñas diferencias. A simple vista son iguales, pero el comando diff -b me arrojaba que no eran iguales. Por ende decidí abrir la imagen de las soluciones en mi programa y comparar los bytes de esta fila por fila con respecto a mi imagen de output. Por ejemplo en el pixel 10 se puede ver una diferencia entre los valores de grises y por ende decidí analizar con mayor detalle lo que sucede en este pixel. En la siguiente imagen se puede ver que en la posición del pixel 10 mi imagen tiene un grisáceo 119 mientras que la imagen final 118.
<img width="1273" alt="Captura de Pantalla 2021-04-28 a la(s) 16 12 11" src="https://user-images.githubusercontent.com/48494298/116466531-99fe0e00-a83c-11eb-898e-c5941dc79773.png">

Entonces imprimí el valor del nodo, gris y área_del nodo cada vez que se accediera a este pixel. El resultado fue el siguiente:
<img width="180" alt="Captura de Pantalla 2021-04-28 a la(s) 16 12 25" src="https://user-images.githubusercontent.com/48494298/116466631-bdc15400-a83c-11eb-8571-1f21fa7c0511.png">

Entonces mi pregunta es si el filtro de aplica de arriba hacia abajo, y los cambios superiores, no afectan el área del nodo en el que me encuentro. Por qué este nodo es afectado por el filtro y cambia a 118 (me supongo que es su padre), si es que su área 110 > 12 (área min) y su valor de grisáceo también es superior a umbral 119 > 40.

Por favor si alguien tiene algún indicio de donde podría equivocándome, gracias!

**Comment by JuanDlugo** [comment]
aclaración: todo esto me pasa en el test 2 área 12 40

**Comment by jtcaraball** [comment]
Mi codigo tambien arroja diferencias de 1 en una cantidad limitada de pixeles en el test 2! Me sumo a la pregunta 👀
