### ISSUE TITLE
[Tarea 1][Informe] Duda eficiencia entre estructuras

### ISSUE THREAD

**Issue by jtcaraball** [IIC2133-PUC/2021-1#153]
Hola! En el enunciado piden determinar que estructura es mas _eficiente_ entre Component Tree y el Max Tree pero no me queda claro a eficiencia en qué. Se busca que respondamos según el costo en tiempo de creación de la estructura o aplicación de filtros o es una pregunta de eficiencia en ocupación de memoria? Me resulta dificil concluir a partir de esto cual gana en eficiencia, como que depende 😞

**Comment by nmcin** [comment]
Hola,

Como dice el enunciado se espera que hagan la compararción de complejidad para construir el arbol y de aplicar los filtros. Debes incluir las diferencias en memoria y en tiempo de ejecución.

**Comment by jtcaraball** [comment]
Osea que hay que implementar un algoritmo para el component tree para cada uno de esos puntos? D:

**Comment by nmcin** [comment]
No es necesario, basta con explicar las diferencias y cómo estas pueden afectar o no en las complejidades.

**Comment by jtcaraball** [comment]
Ya buenísimo! Última consulta, en el enunciado cuando habla de profundiad del árbol se refiere a altura?
