### ISSUE TITLE
[Duda C] - Problema ejecutando mi código

### ISSUE THREAD

**Issue by JaviGuzman** [IIC2133-PUC/2021-1#154]
Hola, estoy tratando de ejecutar mi código y me sale el siguiente error.

![Captura de Pantalla 2021-04-28 a la(s) 19 27 38](https://user-images.githubusercontent.com/48359777/116484781-cc693480-a857-11eb-93be-9ec13534dd44.png)

Esto lo hago luego de ejecutar el comando make.

Alguien me puede ayudar porfa?

**Comment by fadediego** [comment]
Hola!
Una posible causa de eso es que estés importando un módulo .h (como #include "ejemplo.h"), en donde declaras una función, pero no agregas un respectivo archivo ejemplo.c en donde la definas.
Si no es el caso, avísame!
Saludos, Fernando.

**Comment by JaviGuzman** [comment]
Según yo estoy haciendo bien el importar los archivos .h y que estén los respectivos archivos .c, pero no sé si realmente estoy en lo correcto.
Y no, nunca he podido ejecutarlo.
Gracias Fernando por la rápida respuesta :)

**Comment by fadediego** [comment]
No me manejo mucho en Mac. Quizás es lo del permiso, voy a investigar.
Te aviso!

**Comment by TeresitaS** [comment]
Hola! A mi me aparece un problema parecido:
<img width="572" alt="Captura de pantalla 2021-04-29 a la(s) 12 46 23 1" src="https://user-images.githubusercontent.com/62114500/116587967-fcace380-a8e8-11eb-945a-5976b6449897.png">
 Estoy importando image en node y node en el main, no se si lo estoy haciendo bien pero creo que si y no entiendo el problema. [Estoy desde MAC]
