### ISSUE TITLE
Objetivos de tiempo tests easy

### ISSUE THREAD

**Issue by Tomasalvarez15** [IIC2133-PUC/2021-1#156]
Hola!

En el último comunicado uno de los anuncios fue:
"También, hemos decidido que el 4 de 6 puntos de la nota de código será determinada por el resultado de los test easy, es decir, solo con los test easy correctos y dentro del tiempo pueden obtener un 5."

¿A que se refieren con dentro del tiempo? Actualmente me corren los test 3 y 4 en 2 min 56 seg y 26 seg respectivamente. Estoy dentro del tiempo o hago cambios para mejorarlo? Estoy como con 100 tareas así que optimizar mi tiempo entre ellas es importante para mí.

Saludos.

EDIT: Estoy corriendo mi programa en Visual Studio, vale la pena correrlo de otra forma para obtener los tiempos que usarán para evaluar?

**Comment by nmcin** [comment]
Hola,

El tiempo máximo de ejecucción es 10 segundos por test. En general, no debiera ser muy distinto el tiempo que tu obtienes del que se obtiene al evaluar.
