### ISSUE TITLE
[Error git]

### ISSUE THREAD

**Issue by Baelfire18** [IIC2133-PUC/2021-1#157]
Hola! En consola de git de aparecio lo siguiente:
![image](https://user-images.githubusercontent.com/50716449/116601474-8d3ef000-a8f8-11eb-8c2a-27fac37a60b7.png)

- El repo lo he clonado 2 veces (en disntintos directorios) y aparte en el mismo directorio actual tengo una copia hasta cierto punto de mi codigo actual (siendo esta la 3 copia del repo en mi PC entonces)
- Ademas estoy debuggeando usando `lauch.json` en `wsl` como me enseño el ayudante Carlos Paredes.

Desconozco el error de la imagen y no se si puede estar relacionado con alguna de las cosas que comente antes. Me da miedo pitearme un codigo que llevo 40 horas trabajando. Como debo proceder poniendo `yes` o `no`?

**Comment by CarloGauss33** [comment]
Este error puede ocurrir al utilizar git bash y wsl2, para solucionarlo puedes probar hacer commits y push desde la consola de wsl. Luego haces un pull desde git bash

**Comment by Baelfire18** [comment]
Gracias!
