### ISSUE TITLE
[Tarea 1] Profundidad para cálculo de complejidad

### ISSUE THREAD

**Issue by nachobascar** [IIC2133-PUC/2021-1#159]
Hola!! Tengo una duda con la profundidad que piden para el cálculo de complejidad. 
¿Con esa profundidad se refieren simplemente a la altura del árbol? ¿O se refiere a la cantidad de umbrales permitidos? 
Pregunto porque si se referiría simplemente a la altura del árbol, esta estaría limitada a los 128 umbrales posibles, por lo que no me haría mucho sentido al ver el crecimiento del tiempo de ejecución.

**Comment by nmcin** [comment]
Calculala para el peor caso, probablemente donde la altura del arbol sea igual a la cantidad máxima de umbrales. Y en lugar de usar 128, usala como un parámetro *h*.
