### ISSUE TITLE
Error en extensión remote-wsl

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2133-PUC/2021-1#17]
Hola! Tengo un problema con la extensión Remote-WSL lo que pasa es que de un momento a otro esta me comenzó a fallar y me tira el siguiente error 
![Captura de pantalla (800)](https://user-images.githubusercontent.com/62029138/112395834-eace9400-8cdd-11eb-877b-e504f174790f.png)
Probé desinstalar y volver a instalar la extensión sin embargo el error persiste, encontré una issue https://github.com/microsoft/vscode/issues/99517
 en la que mostraban un error similar pero con WSL2 sin embargo no se como aplicar la solución, me refiero a donde colocaría el comando que me indican ahí 
el rm -rf ~/.vscode-server-insiders.
Mi sistema operativo es windows.

[Actualización]:

Desinstale y volví a instalar ubuntu siguiendo los pasos de la guía pero me tira este error, creo que esto era lo que pasaba la otra vez 
![Captura de pantalla (801)](https://user-images.githubusercontent.com/62029138/112406994-080e5d00-8cf4-11eb-94a6-2ad38997c9c3.png)
![Captura de pantalla (802)](https://user-images.githubusercontent.com/62029138/112407046-1d838700-8cf4-11eb-964e-d2f529727394.png)

**Comment by CarloGauss33** [comment]
Hola!
Este problema indica que la instalación de wsl probablemente se corrompio, por lo tanto la mejor opción es reinstalar con los siguientes comandos  en powershell admin

```
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```

**Comment by RonaldoSosa** [comment]
Con eso pude solucionar el problema! Muchas gracias!!!
