### ISSUE TITLE
Tabla de hash con Encadenamiento

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#170]
Hola, tengo la duda de cómo funciona la tabla de hash con Encadenamiento. Es un array donde cada valor será también un array? o tendrá valores de lista ligada?

**Comment by fadediego** [comment]
Hola Camila!

Me parece que se puede de ambas formas. Sin embargo, en clases se menciona la versión en que la tabla es un array donde cada valor es el nodo cabeza de una lista ligada. Esta última forma puede traer beneficios al momento de eliminar elementos (reconectando de manera simple los nodos).

Saludos!

**Comment by Camila-sty** [comment]
Gracias!
