### ISSUE TITLE
Número de casillas para el factor de carga

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#171]
Hola, tengo la siguiente duda;
El n° de casillas para calcular el factor de carga se refiere al tamaño exacto de la tabla de hash?

**Comment by fadediego** [comment]
Hola!

El factor de carga es el ratio n/m, donde n es el número de casillas (entradas) de la tabla de hash (array) que contienen algún elemento, y m es el tamaño total de la tabla de hash. Se calcula sobre el tamaño exacto de la tabla.

Por ejemplo, si tengo una tabla de hash de largo 128, entonces si hay 64 posiciones ocupadas, el factor de carga será 0,5.

Saludos.

**Comment by Camila-sty** [comment]
Ahora me quedó más claro, gracias!
