### ISSUE TITLE
[Contenido] Complejidad Hash con Encadenamiento

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#172]
Hola, tengo una duda con la complejidad de buscar un elemento dado una llave de una Tabla de Hash con Encadenamiento. En clases se vió en el caso promedio se puede considerar O(1), pero esto se puede considerar solo si la función de hash es uniforme no? Si la función de Hash no es uniforme entonces la complejidad de búsqueda en caso promedio es O(factor de carga) o se sigue considerando O(1)?

**Comment by fadediego** [comment]
Hola!

Es un poco complicada tu pregunta. Quizás esto te pueda servir:
https://www.geeksforgeeks.org/hashing-set-2-separate-chaining/
Se señala que, en promedio, la complejidad de inserción es O(1), y de búsqueda y eliminación es O(1 + a), con a el factor de carga.
Si encuentro una demostración la posteo acá.

Saludos!
Fernando.

**Comment by SebaHagedorn** [comment]
Hola! gracias por la info. Lo único que no me quedó claro es: ¿A qué se refiere con que el factor de carga es O(1)?
