### ISSUE TITLE
[Tarea 2] [Duda C] Cómo saber cuánta RAM estoy utilizando

### ISSUE THREAD

**Issue by Tvergara** [IIC2133-PUC/2021-1#174]
Hola, no estoy seguro de cómo ver cuánta RAM está utilizando mi programa para cumplir con la restricción de 1GB en uso. Estoy ejecutando el programa en Ubuntu

**Comment by fadediego** [comment]
Hola!

Puedes correr el comando htop en consola.
Dicho comando te entrega el uso de memoria de cada proceso que estás corriendo.

Saludos!
