### ISSUE TITLE
Invitación de repositorio expirada

### ISSUE THREAD

**Issue by Benjale** [IIC2133-PUC/2021-1#177]
Hola, pensaba empezar la tarea hoy día pero me di cuenta que se me olvidó aceptar la invitación al repositorio cuando llegó. Ahora intente aceptarlo pero me sale que la invitación ya expiró. ¿Cómo podría solucionar mi problema y tener repositorio?

**Comment by Ignacio321** [comment]
hola, yo tengo el mismo problema

**Comment by TrinidadVargas** [comment]
> hola, yo tengo el mismo problema

ya reenvié tu invitación
