### ISSUE TITLE
[Tarea 2] Trabajar con número binarios en C

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2133-PUC/2021-1#178]
Hola. Quería saber como se trabaja con números binarios en C. Por ejemplo, si al realizar una operación entre estos se me entregue otro numero binario, cómo transformar un int a un binario, como concatenar binarios, etc. Busqué y no encontré la forma de trabajo directamente con estos :(

**Comment by nmcin** [comment]
Hola,

Así como se usa la suma y la resta, existen también los operadores de bit (**Bitwise operators**), te recomiendo investigar en internet.
Por ejemplo el AND entre dos números sería: `a & b`, el OR `a | b`, el XOR `a ^ b`. Esto funciona con las representaciones binarias de las variables, te explico con un ejemplo más completo:
```
int a = 5;    // 0b000...00101 (32 bits para un int)
int b = 18;   // 0b000...10010
a | b         // 0b000...10111 = 23
```
