### ISSUE TITLE
Error Soluciones

### ISSUE THREAD

**Issue by gachondoj** [IIC2133-PUC/2021-1#179]
Hola, estaba comparando soluciones y me salia que eran distintas cuando se veian iguales por lo que me meti a revisar y en las imagenes dadas como soluciones los grises son 74 en lugar de 64. Que hacemos con eso?

**Comment by TrinidadVargas** [comment]
Hola @gachondoj desde ayer se encuentran en el siding los test con el valor de gris correcto (64) junto con los test lunatic
