### ISSUE TITLE
Invitación al repositorio de la Tarea 2

### ISSUE THREAD

**Issue by lewebe** [IIC2133-PUC/2021-1#180]
Hola, se me fue aceptar la invitación para el repo de la tarea 2 y expiró. Agradecería que me la pudieran enviar de nuevo.

**Comment by nmcin** [comment]
Hola,

Te envié una nueva invitación

**Comment by nfragav** [comment]
Hola, a mí también me pasó lo mismo. Me la pueden enviar denuevo, porfavor?

**Comment by nmcin** [comment]
Listo

**Comment by Nicobuzeta** [comment]
Hola, a mi tambien me paso lo mismo :(

**Comment by TrinidadVargas** [comment]
@Nicobuzeta listo!
