### ISSUE TITLE
[Tarea 2] Duda con el factor de carga optimo de la tabla hash

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#181]
Hola, se me surge una duda respecto al factor de carga de la tabla de hash que tenemos que implementar.
Como en otro issue dijeron que hay que almacenar todos los subimganes, los subimagenes de tamaño reducido como 1x1, 2x2, tiene muy pocas combinaciones pero puede haber muchos en un imagen, entonces si hasheamos estas subimagenes va a ver muchas repeticiones bajo un hash para una combinacion posible, aumentando mucho el factor de carga.
Entonces queria saber que se podria hacer en esta situacion.
Muchas gracias!

**Comment by nmcin** [comment]
Hola,

De acuerdo al anunciado  no es necesario hacerlo con imagenes de 1x1, el mínimo es 2x2. En cuanto a lo que dices, es posible que ocurra que hayan muchas repeticiones de la misma subimagen y es un caso que se puede manejar igual que cualquier otro. Sobre el factor de carga, este se corresponde con la cantidad de subimagenes guardadas en la tabla y no con la distribución de estas, por lo que no se ve afectado si son todas iguales o todas distintas.

**Comment by chineseJack564** [comment]
Hola, entiendo, pero al tener muchas subimagenes de 2x2 de un mismo tipo,no afectara la uniformidad? Al final como hay que justificar que  la funcion de hash es uniforme?
