### ISSUE TITLE
Gris de los tests

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2133-PUC/2021-1#182]
Hola! Creo que el gris de los test es distinto al que venia en la tarea, ya que me tira error en todos los tests y según yo la estructura es la misma.

**Comment by fmaturanaa** [comment]
Hola! Cambia el valor de 64 por 74. A mi me funcionó eso. (No soy ayudante).

**Comment by TrinidadVargas** [comment]
Hola! @tedroppelmann @fmaturanaa desde ayer se encuentran los test con el valor correcto (GRAY = 64)

**Comment by felipe-barria95** [comment]
Para la entrega final dejamos entonces los valores de gris como 64?

**Comment by TrinidadVargas** [comment]
@felipe-barria95 Si! Como estaba originalmente en el código base
