### ISSUE TITLE
[Tarea 2] Generar números primos

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2133-PUC/2021-1#184]
Hola! Para la tarea, mi función de hash se beneficia bastante si utilizo "buenos" números primos. El tema es que su tamaño depende del tamaño de la imagen misma. Por lo tanto, cómo podría utilizar numeros primos para mi programa? Una opción, es sacarlos de internet, guardarlos en mi programa y encontrar el que más me sirva. Otra opción es similar, pero con una función que genere números primos (suena ineficiente), y la última sería utilizar alguna librería que los calcule/me los entregue.
Qué me recomiendan?
Gracias!

**Comment by nmcin** [comment]
Hola,

Generar números primos efectivamente puede ser lento si los números son grandes, aunque investigando podrías encontar algunos "trucos" para conseguirlos relativamente rápido. Sin embargo, si no necesitas demasiados te recomendaría guardarlos en el programa.

**Comment by Christian-Klempau** [comment]
Okey, muchas gracias!
