### ISSUE TITLE
[Tarea 2] Distribución uniforme

### ISSUE THREAD

**Issue by Baelfire18** [IIC2133-PUC/2021-1#185]
Hola que tan `uniforme` debería ser mi función de hash? Ideé 2 funciones de hash pero su distribución no me tinca tan uniforme:
Para una foto de pixeles 8x8 se verían así mis 2 distribuiciones:
a) 
![image](https://user-images.githubusercontent.com/50716449/120949547-c72ebd80-c712-11eb-90d0-9feae4ab6a23.png)

b)
![image](https://user-images.githubusercontent.com/50716449/120938220-bc0e6a00-c6df-11eb-8bce-1bf389fab052.png)

Son muy poco uniformes o esta bien que estén así?

**Comment by nmcin** [comment]
Hola,

Esa distribución la hiciste con todas las subimágenes de una foto de 8x8?
Puede que tu espacio muestral sea muy acotado, trata de hacerlo para varias imágenes distintas, prueba haciendo imágenes aleatorias.
