### ISSUE TITLE
Función de resize

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2133-PUC/2021-1#186]
Hola. Es estrictamente necesario implementar una función de resize en mi programa? Si ese fuera el caso, como elijo un valor de factor de carga máximo para agrandar la tabla? Por ejemplo, un valor de carga de 4 si utilizo encadenamiento es bueno o malo? Saludos

**Comment by TrinidadVargas** [comment]
Hola! 
> Es estrictamente necesario implementar una función de resize en mi programa?

No es estrictamente necesario ya que nadie revisará tu código, pero si se debe mencionar en el informe el factor de carga máximo que usaste. Un problema que puede traer no implementarlo es pedir extremadamente mucha memoria para los tests más fáciles y tener un factor de carga muy alto en los tests difíciles lo que tendrá consecuencias en el tiempo porque las últimas inserciones no serán O(1).

> como elijo un valor de factor de carga máximo para agrandar la tabla?

En clases se dijo que "con encadenamiento, es aceptable ≈ 1 (o incluso un número entero pequeño)" y que "con direccionamiento abierto, > 0.5 resulta en inserciones y búsquedas muy lentas"

Son valores aproximados porque el factor de carga óptimo es un valor empírico, por lo que hay que probar varias veces con números distintos, y con cronómetro, ver cuál es mejor.

**Comment by tedroppelmann** [comment]
Pero si no implemento una función de resize, ¿a que te refieres con una factor de carga máximo? Esto porque por lo que tengo entendido el factor de carga dependería del tamaño de la imagen inicial. Por ejemplo, lo que hice yo fue graficar como cambia el factor de carga según el tamaño de la imagen y además mencioné que con un tamaño de imagen de 90x90 (imágenes del test hard) tengo un factor de 4, lo que es aceptable. ¿Es suficiente esto como argumento?
