### ISSUE TITLE
[Tarea 2] Dudas con los archivos de test

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#187]
Hola, tengo una duda sobre como se debe reconocer los imagenes similares,
por ejemplo, el test0-1:

![image](https://user-images.githubusercontent.com/69604944/120943587-d8b99a80-c6fd-11eb-9ddd-23d92c563e08.png)
Se ve de 4 pixeles pero en verdad es de 10X10, si queremos buscar la aparicion de este imagen de nuestro imagen principal, solo tenemos que encontrar su ocurrencia en subimagen de 10X10, o es en cualquier escala mientra que se parece al esta imagen?
Desde el enunciado entiendo que para un imagen de mXm, solo encontramos su apariencia en subimagenes de mXm.

**Comment by TrinidadVargas** [comment]
Hola @chineseJack564 Como dice en la issue #168 fue un error en ese test, realmente es de 2x2 y solo deben buscar los insectos del mismo tamaño
