### ISSUE TITLE
[Tarea 2]Duda uso de funcion incremental

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#188]
Hola, 
Para la tarea es obligado usar un hash incremental, si quiero ocupar un hash no incremental habra penzalizacion?

**Comment by TrinidadVargas** [comment]
Hola, nadie revisará tu código por lo que puedes hacer lo que quieras mientras los tests estén correctos y en el tiempo adecuado. Sin embargo no hacerlo incremental significa complejidad extra por lo que no sabemos si correrá dentro del tiempo o no (puedes probar)

Eso si, en el informe se pide 
> Diseñar una función de hash uniforme para una imagen de dimensiones n × n, que pueda calcularse de manera incremental. 

por lo que aunque no lo implementes hagas en el código si debes diseñar la función
