### ISSUE TITLE
[Tarea 0] POSITIVE

### ISSUE THREAD

**Issue by ctronp** [IIC2133-PUC/2021-1#19]
Los hijos de un positivo no deberian pasar a *sospechosos en espera*, es que hasta el color de los recuadros lo confirma.

![image](https://user-images.githubusercontent.com/67880687/112427183-ede67600-8d17-11eb-8aa8-8e8873f96188.png)
![image](https://user-images.githubusercontent.com/67880687/112427303-25552280-8d18-11eb-98a4-a2b50e01901b.png)

**Comment by fadediego** [comment]
Hola!

Creo que no entiendo tu duda. Los sospechosos en espera son los naranjos. En el primer gráfico, como el nodo 2 ahora es positivo, sus hijos pasan a ser sospechosos en espera (naranjos).

Saludos.

**Comment by ctronp** [comment]
Yap gracias, es que m ehabia guiado por el titulo y decia que pasaban a sospechosos los hijos.

**Comment by FloValdes** [comment]
El enunciado dice que los hijos cambian a sospechosos nomás, no a sospechosos en espera. Podrían arreglar el enunciado para que no se preste a confusiones.
Gracias.

**Comment by rbhernandez** [comment]
Hola, ya se encuentra actualizado el enunciado :)
Saludos

**Comment by ctronp** [comment]
Gracias!

**Comment by lfuenzalida2** [comment]
Las personas en `prev` y `next` son contacto estrecho de la persona actual? (por ejemplo, en el primer grafico, 2 es contacto estrecho de 1 y 3?)

**Comment by rbhernandez** [comment]
Hola! los contactos estrechos de un nodo son los hijos de éste, no sus vecinos en la lista ligada.
Para el primer gráfico piensa que el nodo 0 se contagió y sus contactos estrechos fueron la persona 1 (un familiar), la persona 2 (alguien del trabajo) y la persona 3 (alguien X), sin embargo el familiar nunca estuvo en contacto con la persona del trabajo, por lo cual no es su contacto estrecho.

Espero que se haya entendido :)
