### ISSUE TITLE
[Tarea 2][Informe] Uso de diccionario y eficiencia.

### ISSUE THREAD

**Issue by nfragav** [IIC2133-PUC/2021-1#192]
Hola! Quería preguntar si para justificar la eficiencia de uso de una hash table se requiere mostrar un algoritmo o comparación de complejidades, o si, por el contrario, simplemente se espera que se describa en qué parte del proceso se hace más eficiente la ejecución.

Gracias!

**Comment by nmcin** [comment]
Hola,

Basta con que compares como sería la ejecución con y sin tabla de hash, mostrando cual es más eficiente y por qué. Puede ser explicado con palabras o complejidades mientras que quede bien justificado.
