### ISSUE TITLE
[Tarea 2] tests de Lunatic incorrectos

### ISSUE THREAD

**Issue by Tvergara** [IIC2133-PUC/2021-1#194]
Hola, me parece que hay un error en los test de Lunatic. Tengo todo bien en los Easy, Medium y Hard, pero cuando llego a Lunatic me tira incorrecto en básicamente todo. Por ejemplo, el ```test_1_1.png``` busca el siguiente insecto:
![image](https://user-images.githubusercontent.com/58240958/121445613-d0609a00-c95f-11eb-87ef-050cdc7eb912.png)
Sin embargo, el supuesto output correcto es:
![image](https://user-images.githubusercontent.com/58240958/121445654-e5d5c400-c95f-11eb-9875-8e6842172156.png)
Lo cual no me pareciera tener sentido. Puede ser que hay algún error en estos tests?

**Comment by furzuadr** [comment]
Hola! Me sumo a la pregunta, me pasó exactamente lo mismo. Paso los Easy, Medium y Hard, pero no paso ninguno de los Lunatic. Revisé y hay varios casos como el que indicaron arriba, que no tiene sentido el output con respecto a lo que piden!

**Comment by Nicobuzeta** [comment]
Yo estoy pasando todos los tests + el test 6 de lunatic, pero el resto de los lunatic me tira mal. De lo que veo, las dimensiones de las soluciones del lunatic estan mal (por lo menos del test_1). 
test_1.png -> 133x133
out_1_0.png -> 163x163

**Comment by DiegoEmilio01** [comment]
Me pasa lo mismo que a nico. Además, sumar el dato que en las soluciones faltan las del Test 5 de los Lunatic

**Comment by benjaminlillo** [comment]
A mi también me pasa lo mismo, de lunatic solo me pasan los tests 6.

**Comment by TrinidadVargas** [comment]
Hola @Tvergara @furzuadr @Nicobuzeta @DiegoEmilio01 @benjaminlillo Sorry por el error, ya volví a subir las soluciones de los tests Lunatic y los comparé con uno de sus compañeros.
