### ISSUE TITLE
[Tarea 2] Subir los tests al repositorio

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2133-PUC/2021-1#195]
Hola!
¿Hay que subir los archivos de test al repositorio? ¿Y otros archivos como `check.py` `output` y `solutions` ?

**Comment by nmcin** [comment]
Hola,
Idealmente no los subas. En tu repositorio debiera haber lo mínimo para compilar tu programa (src + Makefile) y ojalá nada más.

**Comment by benjaminlillo** [comment]
Yap gracias!
