### ISSUE TITLE
[TESTS] - Puntaje parcial

### ISSUE THREAD

**Issue by tomasft0410** [IIC2133-PUC/2021-1#197]
Hola quisiera saber si hay puntaje parcial en los test. Por ejemplo si en el test Medium 3, el check.py dice que tengo 187/190 Correct y 3 Incorrect, se considera este puntaje para la nota, o se considera como fallido.

**Comment by TrinidadVargas** [comment]
Hola, se consideran como un único test, por lo que deben estar todas las consultas correctas. Esto te pasa únicamente en este test o en todos? Te recomiendo que revises los casos bordes de tu programa para que encuentres posibles errores

**Comment by tomasft0410** [comment]
Me pasa esto en alguno test, pero por ejemplo el Medium 5 me aparece 250/250 correctos. Voy a revisar que puede estar mal, muchas gracias
