### ISSUE TITLE
[Tarea 2] Duda RAM utilizado

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#199]
Hola! Podrían explicar cómo revisar el RAM utilizado en el proceso mediante HTOP, que estoy medio perdido de cómo interpretar el %MEM.
Gracias!

**Comment by Aloncarrasco** [comment]
Para ver lo de la memoria ram se meten en el admin de tareas y van a la parte de rendimiento y ahí ven la memoria. cuando corren su programa toman el uso de memoria en punto más alto y le restan el uso de memoria mientras no corre nada.
![image](https://user-images.githubusercontent.com/62113089/121792397-39dfe300-cbc2-11eb-8e35-1f62ff2e6844.png)

**Comment by SebaHagedorn** [comment]
Gracias!
