### ISSUE TITLE
[TAREA 0] Main y rutas a nodos

### ISSUE THREAD

**Issue by isiguelfand** [IIC2133-PUC/2021-1#20]
Hola! Por lo que entiendo no deberíamos modificar mucho el archivo main, ya que está el espacio para las cosas que debemos implementar. Por esto, no entiendo como deberíamos usar las rutas, por que por lo que veo solo se va guardando el id de cada persona de la ruta en cada iteración en una variable "int" y después en esta misma se guarda el id siguiente. No estoy segura si lo estoy entendiendo mal o si debería modificar algo dentro de la iteración. 
Gracias!

**Comment by TrinidadVargas** [comment]
Hola, el archivo ```main.c``` incluye únicamente la lectura de archivos. Se usó la variable ```contact_id``` para mostrar como se lee el archivo, pero ustedes tienen que ver de que forma les conviene guardar o usar esos datos para resolver el problema. Para eso si tienes que modificar lo que está dentro de la iteración.
