### ISSUE TITLE
[Tarea 2] Forma de corregir

### ISSUE THREAD

**Issue by Baelfire18** [IIC2133-PUC/2021-1#200]
Hola tengo una duda a la hora de corregir nuestras tareas. Tengo entendido que las corren en un servidor online, ahí tambien corren nuestro makefile. 
- ¿Podemos modificar el makefile nosotros (tal como lo hizo un ayudante [acá](https://youtu.be/e9wUO9AAj6s?t=490))? o ¿ustedes tienen uno propio que lo usan para compilar nuestras tareas (las corren con el optimizador en en -03 cierto)?
- Tambien las variables BLACK, GRAY y WHITE son fijas? Por que en algunas partes tengo hardoceados su valores, deberían siempre debender del valor actual?
- Tambien ¿cómo vemos la memoria o tiempo que consume en algo similar a su servidor online?

**Comment by nmcin** [comment]
Usamos la Makefile que suben al repositorio. Las constantes BLACK, WHITE y GRAY las entregamos para facilitar el código, pero lo que importa son los valores que usen. Puedes suponer que la memoria y tiempo serán similares a lo que obtengas en tu computador.
