### ISSUE TITLE
[Tarea 3]  Aristas (tipo de valores que se entregan y cantidad de veces que aparecen)

### ISSUE THREAD

**Issue by pablosbw** [IIC2133-PUC/2021-1#203]
Hola, tengo un par de dudas preliminares antes de comenzar a programar:

1. Las aristas con las que trabajamos tienen costos siempre positivos enteros o podrían ser únicamente positivos o enteros o sin restricción? Por ejemplo si tenemos 3 nodos es válido que el camino 1-2 tenga costo 2.3, o que la arista tenga costo -1. 
2. Mi otra duda está relacionada con la entrega de información, ¿Existen aristas duplicadas? nuevamente tomando el ejemplo anterior, si me entregan que la arista 1-2 tiene costo 3, en las próximas aristas ¿podría aparecer una arista 1-2 con costo distinto?
3. ¿Existen un costo máximo para una arista?

Gracias de antemano!

**Comment by lucas-valenzuela** [comment]
Hola Pablo, te comento tus dudas:

1. Los costos son enteros positivos.
2. No entregaremos haber aristas duplicadas.
3. No hay límite de costo máximo

Suerte con la entrega :) 🍐

**Comment by Ignacio321** [comment]
En el test_02 aparece en la línea 1 la arista '0 2 5' y en la línea 5 la arista '2 0 3', ¿es arista duplicada o no?

**Comment by nico-mac** [comment]
Hola, efectivamente ese test tiene un error, no lo tomen en consideración.
