### ISSUE TITLE
[Tarea 3] Comparar los output y soluciones

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2133-PUC/2021-1#204]
Hola, ¿debería satisfacerme el solamente comparar el costo total final o habrá alguna forma de asegurar que mi output está bien?

**Comment by TrinidadVargas** [comment]
Hola @DiegoEmilio01 

La única forma %100 segura de saber si el output está correcto es conectando los nodos, pero como esa es la tarea no les podemos dar un programa que lo corrija. 
Además del costo te puedes fijar si la cantidad de carreteras es la misma que la cantidad de nodos a conectar o puedes hacer tu propio programa que revise que todas los nodos estén conectados
