### ISSUE TITLE
[Tarea 3][Bonus] Duda Valgrind Warning: client switching stacks?

### ISSUE THREAD

**Issue by DiegoEmilio01** [IIC2133-PUC/2021-1#205]
```
==26532== Warning: client switching stacks?  SP change: 0x1f...--> 0x1f...
==26532==          to suppress, use: --max-stackframe=2516344 or greater
```
Hola, Valgrind me tira esta advertencia al correr los test muy grandes. Intente reducir la cantidad de memoria allocada respecto a tareas anteriores así que utilicé poco malloc o calloc. El tema es que ahora me da warnings de stack en vez del heap. Me surgen 2 preguntas:
- ¿Debería hacer algo para solucionar esto en cuanto a correctitud del código?
- ¿Este warning evita obtener el bonus?

**Comment by TrinidadVargas** [comment]
Hola @DiegoEmilio01 Por lo que veo eso es un warning, pero para obtener el bonus debes obtener los siguientes resultados al correr ```valgrind ./tarea test output```

```All heap blocks were freed -- no leaks are possible``` y  ```ERROR SUMMARY: 0 errors from 0 contexts```
