### ISSUE TITLE
[Tarea 3] Duda Output Tests

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#206]
Hola! Tengo una duda con respecto los outputs de las soluciones de Siding, en el enunciado se nos indica que se deben escribir los caminos elegidos en el mismo orden en el que aparecieron en el input. Yo entiendo que entonces se tienen que escribir los caminos en orden. La solución del test_01.txt cumple con lo del enunciado, pero las otras soluciones entregan los caminos al parecer en el orden en el que fueron elegidos. Quería confirmar cuál es el orden esperado en nuestra solución.
Gracias!

**Comment by TrinidadVargas** [comment]
Hola @SebaHagedorn en la parte de output dice

> **No** importa el orden de las carreteras en el output y puede haber más de una solución correcta. En el ejemplo, podemos cambiar 6 por 10 o 11.

**Comment by SebaHagedorn** [comment]
Ah perfecto, entonces se corregirá el costo final como test correcto?

**Comment by TrinidadVargas** [comment]
@SebaHagedorn 
nop, nosotros revisaremos que todas las ciudades estén conectadas, por lo que hay más de una posible solución. Pero como revisar que todas las ciudades estén conectadas es casi lo mismo que hacer la tarea no les podemos dar un programa que revise si está bueno o no.

**Comment by SebaHagedorn** [comment]
Ya perfecto, Gracias!
