### ISSUE TITLE
[Tarea 3] Duda centros de distribución

### ISSUE THREAD

**Issue by mserranob** [IIC2133-PUC/2021-1#207]
Hola! es neceseario que todos los centros de distribución esten conectados a al menos 1 cliente? o puede quedar un centro de distribución sin repartir a nadie?

**Comment by TrinidadVargas** [comment]
Hola!
En el enunciado dice
>  decidir qué carreteras elegir para que todo cliente se conecte con un centro de distribución y que el costo total sea el mínimo. 

Por lo que puede quedar un centro de distribución (o más) sin repartir
