### ISSUE TITLE
[Tarea 3] Duda con informe

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#209]
Hola! sobre el informe se nos pide explicar y comparar en término de complejidad e implementación. La implementación cómo se espera que la expliquemos? en relación a estructuras de datos utilizadas o más enfocado en la lógica que utiliza cada algoritmo?. Además, en el primer pie de página se indica que es en un máximo de 2 planas, esto sería para el informe completo o para cada algoritmo?
Gracias!

**Comment by nico-mac** [comment]
Hola,
Se espera una explicación (no muy profunda) de la lógica del algoritmo y en caso de que use estructuras especiales también debes mencionarlas y considerar sus complejidades.
Las 2 planas son para el informe completo.

**Comment by DiegoEmilio01** [comment]
Hola @nico-mac ! Pueden habilitar el cuestionario para entregar el informe porfa, para tener la tarea entregada y así desconectarse de ella 😅

**Comment by TrinidadVargas** [comment]
@DiegoEmilio01 lo habilito ahora

**Comment by DiegoEmilio01** [comment]
Muchas graciass, a ti y al equipo docente también!

**Comment by SebaHagedorn** [comment]
Muchas gracias por la respuesta @nico-mac 😄
