### ISSUE TITLE
Duda con person_route

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#21]
Hola,
No entendi muy bien como esta definido el (2 3 5) en el ejemplo, entendi que el 5 significa persona con id 5. Pero el 2 y 3 no lo logro a ver, no se si pueden explicarlo un poco mas. Muchas gracias!

![image](https://user-images.githubusercontent.com/69604944/112544358-aacae800-8d95-11eb-8272-e28631fddf36.png)

**Comment by fadediego** [comment]
Hola!

El primer número es la profundidad en donde se encuentra el nodo objetivo (en este caso 2). Los números que le siguen son los id por los cuales se va "bajando por el árbol". Así, el primer número después de la profundidad (3 en este caso) estará en profundidad 1, el segundo número en profundidad 2, y así. 

Saludos!!

**Comment by chineseJack564** [comment]
En este caso nuestro nodo objetivo es el nodo 5? y sigo sin entender que significa el 3, significa que vamos a pasar por nodo 3?

**Comment by fadediego** [comment]
Claro, en el ejemplo el nodo al que se quiere llegar es al nodo 5. El flujo es el siguiente:
- Tomas la profundidad (2 en este caso).
- Tomas el número que viene posterior a la profundidad (3 en este caso). Del nodo raíz (id 0) revisas sus contactos estrechos, hasta encontrar el nodo con id igual a dicho número.
- Tomas el siguiente número (5 en este caso). De los contactos estrechos del nodo anterior (3), buscas aquel que tenga id igual al número (5).
- Como no hay más números en el input, llegaste al nodo que estabas buscando.

La razón de las flechas grises del ejemplo, es que probablemente en tu implementación no puedas llegar directamente al nodo hijo buscado (por ejemplo, pasar del nodo 0 al nodo 3). Por eso, tienes que buscar exhaustivamente.

**Comment by chineseJack564** [comment]
Perfecto ahora me quedo mas claro, muchas gracias!

**Comment by fadediego** [comment]
Perfecto. Edité un poco la respuesta, porque después de la ruta viene más input. Por eso, edité el último punto. Llegas al nodo que estás buscando cuando estás en el nodo de profundidad indicada.

**Comment by chineseJack564** [comment]
ahora me surgio otra duda de ruta
![image](https://user-images.githubusercontent.com/69604944/112548845-a4d80580-8d9b-11eb-907c-e85ac6566cd8.png)
El 1 2 en azul significa el segundo nodo de profundidad 1 ?
El 2 en rojo significa que se agrega 2 nodos nuevos?

**Comment by TrinidadVargas** [comment]
Hola, si como dices el 1 2 en azul significa que es una ruta con profundidad 1, **pero** se agregan al nodo con **id 2**. El 2 rojo es que se agregan 2 nodos.

**Comment by chineseJack564** [comment]
Me surgio otra duda respecto a este tema, lo que entendi esque el person route puede tomar un largo indefinido, por lo tanto en python se porgramma como reciben una lista:
![image](https://user-images.githubusercontent.com/69604944/112875568-bb7fa480-909a-11eb-92c6-5def63b1508b.png)
Sin embargo en el ejemplo de input muestra algo asi:
![image](https://user-images.githubusercontent.com/69604944/112875648-d5b98280-909a-11eb-9eb6-04d7c5db4124.png)
Entonces eso significa que tenemos que hacer algo en main para cuando nos llega el input, guardar los posiciones correspondiente del person_route en un arry y luego usarlo en la funcion?

**Comment by nmcin** [comment]
Hola,

Tu debes decidir como usar el input dentro de tu código, lo que tu preguntas es parte de lo que debes resolver en la tarea.
