### ISSUE TITLE
[Tarea 3] Calles diferentes, mismo costo total (diferentes soluciones)

### ISSUE THREAD

**Issue by Brocoleta** [IIC2133-PUC/2021-1#210]
Hola, estoy viendo que pueden haber diferentes soluciones, por lo que se me hace imposible verificar que esta bien lo que estoy haciendo, solamente puedo comparar costos totales. Por ejemplo en el test 1, se podria cambiar la calle 10 por la 6 y la solucion seguiria siendo el minimo.

PD: Puede haber una posibilidad de que el test 3 este malo?

**Comment by nico-mac** [comment]
Hola,
Pueden haber varias posibles soluciones como mencionas, lo importante es que tengan el costo mínimo y que todos los clientes queden conectados a un centro. Esto se mencionó en la issue #206 .

**Comment by felipe-barria95** [comment]
Hay algun orden en especifico el cual uno deba escribir el numero de las rutas en el archivo result? Es decir, los caminos deben estar conectados cuando uno los escribe en el archivo o pueden estar desordenada la escritura al archivo solo con tal que la ruta cumpla con MST?

**Comment by TrinidadVargas** [comment]
@felipe-barria95 no, pueden estar en cualquier orden mientras la primera linea del output sea el costo
