### ISSUE TITLE
[Tarea 3] clasificación de los tests

### ISSUE THREAD

**Issue by Tngarrido** [IIC2133-PUC/2021-1#212]
Hola, para la tarea se evaluarán todos estos tests ?
![image](https://user-images.githubusercontent.com/42189869/124312032-ab191300-db3c-11eb-8620-89a819d9d194.png)
O hay algunos tests que corresponden a los test Easy ? que según el enunciado de la tarea no se evaluarán ? 
Gracias de antemano!

**Comment by MGilB** [comment]
Creo que dijeron en discord que los tests 1al 3 son easy, 4 al 8 medium y 9 al 13 hard

**Comment by TrinidadVargas** [comment]
@Tngarrido  exacto! Hasta el 3 son easy, el resto medium y hard. Valen todos lo mismo y son crecientes en dificultad
