### ISSUE TITLE
[Tarea 3] Duda con el tiempo de ejecución

### ISSUE THREAD

**Issue by MGilB** [IIC2133-PUC/2021-1#213]
Hola, quería saber si se puede obtener un puntaje parcial por el tiempo. En mi caso la parte mas ineficiente es el crear todos los datos, nodos y carreteras, pero en encontrar la ruta optima mi código es muy rápido.

Medí por cronometro en mano, así que algo de error hay, pero mi programa se demora en el test_13 **65.63 segundos** en crear los datos y después **1 segundo** en encontrar la ruta óptima.

**Comment by MGilB** [comment]
Los tests medium los corre dentro del tiempo esperado

**Comment by TrinidadVargas** [comment]
Hola @MGilB, no hay puntaje parcial
Si se demora mucho en construir el grafo creo que puede ser porque pides memoria muchas veces (estoy suponiendo ya que esa es la operación más costosa de construir el grafo) Si ese es el caso tal vez puedes pedir memoria una vez para las ciudades y una vez para las carreteras y guardarlos en un array
