### ISSUE TITLE
[Tarea 3] Warning: client switching stacks?

### ISSUE THREAD

**Issue by Christian-Klempau** [IIC2133-PUC/2021-1#215]
Hola!
El programa me está funcionando bien con los tests, pero noté que Valgrind me arroja el siguiente warning para los tests grandes (del 10 en adelante):

```
Warning: client switching stacks?  SP change: 0x1ffedffc10 --> 0x1ffefffbd0
==3326==          to suppress, use: --max-stackframe=2097088 or greater
```
Lo entiendo como que el stack se llenó y utilizó otro stack para complementar. ¿Hay algo que pueda hacer? Podría correr la tarea cambiando el `max-stackframe` pero en la corrección automática va a fallar. 
P.D: trabajo con la mayoría de las cosas en stack, porque no tiene mucho sentido guardarlas en el heap ya que viven solo entre un par de funciones. ¿No tengo otra opción que utilizar el heap aunque no lo necesite o hay otra vía?

**Comment by nico-mac** [comment]
Hola,

Si estás guardando un array de tamaño muy grande en el stack, es mejor allocarlo en el heap. El stack tiene límites de memoria mucho más acotados que el heap.

**Comment by Christian-Klempau** [comment]
Hola!
Todo el grafo lo tengo en el heap, y los arrays están en heap también. ¿Que otra cosa podría ser?

**Comment by nico-mac** [comment]
La lista de aristas?

**Comment by Christian-Klempau** [comment]
Sí, tanto la lista de aristas como los vértices están guardados (malloc) en el heap.

**Comment by Christian-Klempau** [comment]
Si no logro solucionar el error, influye en algo en la corrección o da lo mismo? Sólo perdería el bonus de valgrind?

**Comment by nico-mac** [comment]
Si el programa genera el output correcto y no se cae (segmentation fault) no hay ningún problema. Incluso puedes tener el bonus de valgrind si no hay leaks de memoria (All blocks freed)

**Comment by Christian-Klempau** [comment]
Perfecto, muchas gracias!
