### ISSUE TITLE
[Tarea 3] Bonificación

### ISSUE THREAD

**Issue by Baelfire18** [IIC2133-PUC/2021-1#216]
Hola vengo a preguntar si en esta tarea habrá cierta bonifiación aparte de la clásica de liberar bien la memoria. Por ejemplo, mi algoritmo lo hice muy eficiente, por lo que me pregunto si tambien habrá bonificación por tiempo de ejecución.
Gracias!

**Comment by nico-mac** [comment]
Hola, solo el bonus de memoria.
