### ISSUE TITLE
Supuestos T3

### ISSUE THREAD

**Issue by acpopper** [IIC2133-PUC/2021-1#218]
Hola! Unas dudas respecto al input de la tarea.

1. Puedo suponer que todos los nodos del grafo del input estarán conectados? O puede darse que haya algun(os) nodo(s) que formen otro grafo separado?

2. Podría darse el caso de que al llegar a un mst como solucion, quede un centro de distribucion "aislado"? Por ej. Si hay dos centros de distribucion, podria ser una solucion que solo uno se conecte a todos los clientes (directa o indirectamente), y el otro quede como un nodo solo?

Gracias!

**Comment by TrinidadVargas** [comment]
Hola!
1. Si puede haber nodos que no sea posible conectarlos con las rutas entregadas, pero siempre se podrá conectar una ciudad a un centro de distribución.
2. Si, todas las ciudades se deben conectar a un centro, pero no todos los centros deben distribuir a una ciudad.
