### ISSUE TITLE
[TAREA 3] Duda formato output y tiempo corrección

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2133-PUC/2021-1#219]
Hola! tengo 2 consultas.
La primera es si hay algún formato específico para los outputs obtenidos. Tenía pensado dentro de una carpeta output ir guardando los outputs de la siguiente manera:
output/test_01.txt
output/test_02txt
etc.

Mi segunda duda es con respecto a los 10 segundos tope del algoritmo. Quería saber si este tiempo lo miden con o sin valgrind. Porque la verdad que este último influye bastante en el tiempo de ejecución. 

Gracias!

**Comment by TrinidadVargas** [comment]
Hola! 
Sobre el primer punto: se debe correr con `./dewey network output` y generar un archivo con el mismo nombre que `output`
Si quieres que se te creen los archivos de output en una carpeta puedes escribir la ruta completa en el lugar de output
Sería `./dewey tests/test_01.txt output/test_01.txt`

Lo segundo, se considera los 10 segundos **sin** valgrind

**Comment by JuanDlugo** [comment]
perfecto! muchas gracias!!
