### ISSUE TITLE
Duda CORRECT

### ISSUE THREAD

**Issue by Brocoleta** [IIC2133-PUC/2021-1#22]
Hola, en la función 0.5 CORRECT dice que en caso de que el padre este contagiado sus nuevos hijos que estén en estado sospechoso pasaran a sospechoso en espera, mi pregunta es si son solo los hijos directos o puede ser un hijo de un hijo por ejemplo?

**Comment by lucas-valenzuela** [comment]
Hola!
Solo se aplica a los hijos directos el cambio de estado a sospechoso en espera. En caso de que algunos de estos hijos resulte contagiado, se debe seguir el procedimiento normal con sus respectivos hijos
