### ISSUE TITLE
[Duda C] Problema con #include

### ISSUE THREAD

**Issue by josejimenezp** [IIC2133-PUC/2021-1#23]
Hola, tengo este problema que me sale en VSCode. Cuando ocupo un MakeFile no tengo problema pero no logro compilar con el gcc :(
![image](https://user-images.githubusercontent.com/48298035/112569584-3b6bed00-8dc3-11eb-9985-02cba4b92ae3.png)

**Comment by CarloGauss33** [comment]
@josejimenezp si estas utilizando wsl o Ubuntu debes correr 
``` sh
sudo apt-get update
sudo apt-get install libc6-dev
```

Con estos 2 comandos se actualizaran todos los ficheros y se agregaran las librerías faltantes en caso de no estar

**Comment by josejimenezp** [comment]
> @josejimenezp si estas utilizando wsl o Ubuntu debes correr
> 
> ```shell
> sudo apt-get update
> sudo apt-get install libc6-dev
> ```
> 
> Con estos 2 comandos se actualizaran todos los ficheros y se agregaran las librerías faltantes en caso de no estar

Me sale esto :c

![image](https://user-images.githubusercontent.com/48298035/112666539-0e5b2100-8e3b-11eb-8192-26c594ce1368.png)

**Comment by CarloGauss33** [comment]
Ejecuta
```
sudo apt-get upgrade
```
¿Que mensaje te aparece al ejecutar Make?
El subrayado de vscode puede deberse a que estas de forma local editando archivos (desde windows) y tecnicamente en windows no tienes las librerias, si no que estan en wsl. para eso has de usar remote-wsl

**Comment by josejimenezp** [comment]
> Ejecuta
> 
> ```
> sudo apt-get upgrade
> ```
> 
> ¿Que mensaje te aparece al ejecutar Make?
> El subrayado de vscode puede deberse a que estas de forma local editando archivos (desde windows) y tecnicamente en windows no tienes las librerias, si no que estan en wsl. para eso has de usar remote-wsl

Buena era lo último, del remote-wsl. Muchas gracias :)
