### ISSUE TITLE
Duda Enunciado

### ISSUE THREAD

**Issue by milosoria** [IIC2133-PUC/2021-1#24]
Hola! Me surgió la duda si es que una persona recuperada puede volver a contagiarse, de no ser así no se considera al cambiar los estados en el evento POSITIVE, no?
Gracias!

**Comment by nmcin** [comment]
Hola,

Una persona solo se puede contagiar una vez. Está especificado en el enunciado, entre los aspectos relevantes del arbol.

**Comment by milosoria** [comment]
Gracias, tengo otra duda respecto a cuáles elementos se consideran contactos estrechos, el nodo padre, los nodos hermanos y hijos?

**Comment by nmcin** [comment]
La relación padre-hijo corresponde a un contacto estrecho. Los nodos hermanos no son contactos estrechos entre ellos.
