### ISSUE TITLE
Duda uso de structs en funciones

### ISSUE THREAD

**Issue by Baelfire18** [IIC2133-PUC/2021-1#25]
Hola esta jugando con structs antes de la tarea para soltar un poco la mano y me encontré con un problema:
```
#include <stdio.h>

typedef struct dog
{
   char* name;
   int age;
   int good_boy;
   struct dog* friend;
} Dog;

void dog_print(Dog* dog)
{
   Dog *perro = dog;
   printf("Hola soy un can llamado %s, tengo %i años y ", perro->name, perro->age);
   if (perro->good_boy) printf("soy un buen chico\n");
   else printf("soy un mal chico :(\n");
}

int main() {
   printf("Hello, world!\n");
   Dog A = {"John", 3, 1, NULL};
   Dog B = {"Jane", 5, 1, NULL};
   A.friend = &B;
   B.friend = &A;
   // void dog_print(Dog A);
   dog_print(A);
   
  return 0;
}```
No se como hacer funcionar la funcion `dog_print` si le paso el puntero y luego como lo manejo dentro.

**Comment by nmcin** [comment]
Hola,

Hiciste bien la función `dog_print`, sin embargo para llamarla debes entregarle un puntero a `Dog A`.
Al usar `dog_print(A);` le estás pasando el `struct dog` como argumento.
Para pasarle el puntero a `Dog A`, debes llamarla con `dog_print(&A);`.
El símbolo `&var` significa "la dirección en memoria de la variable var".

**Comment by Baelfire18** [comment]
Buenisimo gracias primo!
