### ISSUE TITLE
[Tarea 0] Duda sobre NEGATIVE

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2133-PUC/2021-1#27]
¿Qué sucede con el contador de IDs cuando una persona y sus nodos hijos son eliminados del árbol?, ¿no tengo que modificarlo si es eliminado un nodo con el mayor ID para luego asignárselo a cualquier contacto que se agregue posteriormente con ADD_CONTACTS?

**Comment by fadediego** [comment]
Hola Jorge,
Por simplicidad, los id que eliminaste no se ocupan de nuevo.
Saludos!
