### ISSUE TITLE
Tests tarea 0

### ISSUE THREAD

**Issue by Tngarrido** [IIC2133-PUC/2021-1#28]
Hola!! he descargado la carpeta zip correspondiente a los tests de la tarea cero y en está solo me aparecen los tests Easy. por ende, creo faltan los demás (Medium y Hard). También me pregunto de si entregarán alguna carpeta con los resultados que debería tener cada tests, para asegurarnos de que el código este funcionando correctamente. Saludos!!

**Comment by fadediego** [comment]
Hola!
El resto de los tests los tenemos casi listos, los subiremos pronto. Voy a consultar si subiremos las soluciones.
Saludos!

**Comment by bmurtagh01** [comment]
Hola,
Van a subir soluciones de algunos test, de un par fáciles por ejemplo o medianos?
