### ISSUE TITLE
[Duda C] Problemas con include en modulos

### ISSUE THREAD

**Issue by MGilB** [IIC2133-PUC/2021-1#29]
Hola estoy tratando de hacer `#inlcude <stdio.h>` en un modulo aparte del main y me tira el mismo error que en la issue #23. Ejecuté los dos comandos que se mencionan y tuve el mismo output que mi compañero. Sin embargo al ejecutar el `make` compila sin problemas el `main.c`.

Estoy usando vscode con la extensión de remote-wsl.

Me tira el mismo error al tratar de importar un modulo personal

**Comment by CarloGauss33** [comment]
@MGilB  no entiendo a que te refieres con "modulo personal", si te refieres a un archivo .h creado por ti, fíjate en que lo importas con 

```
#include "../path_relativo/al/archivo.h"
```

recuerda que el 
```
#inlcude <file.h>
```

Es reservado para headers que están en el path de C en si (algo similar a las librerías que se instalan en python).

Si es que esto no soluciona el problema, por favor envía el error para así entender mejor tu problema. (En caso de que el error contenga fragmentos importantes de tu código, comunica tu problema en el Discord para que un ayudante pueda ver el problema)

**Comment by MGilB** [comment]
La duda que tenía era que en ciertos archivos no me dejaba usar `#include <...>` ni `#include "..."`, pero ahora funciona todo. Tal vez era un error en otra parte. Gracias igual!
