### ISSUE TITLE
[Tarea 0] Sobre NEGATIVE 

### ISSUE THREAD

**Issue by FranciscoCabello** [IIC2133-PUC/2021-1#30]
Que hago en el caso que una personaX que se realizo un test y este es negativo (debo eliminar el arbol hacia abajo) pero si en un nivel mas profundo del arbol existe un contagiado2? 

- Elimino la rama del arbol de todos modos.
- La rama con el contagiado2 la subo al nivel de la personaX.

**Comment by lucas-valenzuela** [comment]
Debes eliminar la rama completa, desde el sospechoso en espera que resultó negativo, sus hijos, nietos y así sucesivamente. Se asume que los descendientes de un negativo nunca serán contagiados

**Comment by chineseJack564** [comment]
Hola tambien tengo una duda respecto al Negative, si el enunciado me dice que elimina la persona, que pasa con el inform dps de Negative?

- La persona negativo sale con un estado 4, eliminando sus hijos?
- Tanto la persona como su hijo no salen en el inform?

**Comment by nmcin** [comment]
Ni la persona ni sus hijos deberán aparecer en INFORM.
