### ISSUE TITLE
[Tarea 0] Uso de librerías

### ISSUE THREAD

**Issue by benjaminlillo** [IIC2133-PUC/2021-1#31]
Hola! ¿Se pueden utilizar otras librerías aparte de las que salen en los videos de intro c? Por ejemplo `string.h`, que entrega una función para concatenar strings.

Saludos!

**Comment by rbhernandez** [comment]
Hola, sí puedes usar otras librerías, lo único importante es que no tengas que instalar nada adicional y te compile con _make_.

Saludos!

**Comment by benjaminlillo** [comment]
Ok, gracias!
