### ISSUE TITLE
[Duda C]

### ISSUE THREAD

**Issue by jtcaraball** [IIC2133-PUC/2021-1#32]
Hola! Tengo una pregunta sobre cómo declarar un array de arrays de tamaño dinámico de structs dentro de un struct. He visto que si por ejemplo queremos declarar un array de arrays de ints usaríamos alto como:
``` 
struct mystruct {
    int** array_of_ints;
}
```
En el caso de un struct (que nos gustaria guardar como un puntero) sería algo cómo esto?
```
struct mystruct {
   otherstruct*** array_of_structs;
}
```

Muchas gracias!!
Saludos :)

**Comment by lucas-valenzuela** [comment]
Hola, 
Es justamente parte de la tarea que resuelvas cómo debes implementar el array de arrays que guarde a los punteros, así que no podemos decirte si efectivamente eso es correcto. Te recomiendo probar para comprobar si eso funciona con un arreglo de arreglos pequeño.
Suerte!
