### ISSUE TITLE
[Duda C]

### ISSUE THREAD

**Issue by PDominguezW** [IIC2133-PUC/2021-1#33]
Mi programa me manda el error 'Segmentation fault (core dumped)' cuando utilizo malloc en el init de persona, pero solo cuando es la 7ma persona que inicializo. El malloc nisiquiera devuelve el puntero NULL, solo se cae el programa,.

**Comment by nmcin** [comment]
Hola,

Segmentation Fault significa que estas accediendo a una dirección de memoria no permitida. Puedes usar valgrind para revisar con detalle los errores de memoria de tu programa y ver que esta haciendo que tu programa se caiga.
