### ISSUE TITLE
[Tarea 0] Duda sobre prints a consola

### ISSUE THREAD

**Issue by nachobascar** [IIC2133-PUC/2021-1#34]
Hola, tengo una duda de si es necesario hacer prints de la función que se está usando (además de crear el archivo de salida), ya que en el template se imprimen diversos mensajes, pero eso genera que el codigo sea mucho más lento.
¿Podemos eliminarlos?

**Comment by nmcin** [comment]
Hola,

Si puedes eliminar los prints.
