### ISSUE TITLE
[Tarea 0] Ausencia códigos "Por Implementar"

### ISSUE THREAD

**Issue by gachondoj** [IIC2133-PUC/2021-1#35]
Hola, puede ser que falte algun "Por Implementar" en el archivo main.c? Add_contacts, Positive y Negative no lo tienen y creo que deberian tenerlo

**Comment by nmcin** [comment]
Hola,

Tu programa efectivamente debe implementar **TODOS** los eventos descritos en el enunciado, incluyendo los que no tengan un `/* Por Implementar */` en el código base.

**Comment by MGilB** [comment]
Para implementar los eventos restantes hay que usar los métodos ya hechos o podemos crear métodos nuevos?

**Comment by nmcin** [comment]
Puedes usar métodos nuevos o no, según estimes conveniente.
