### ISSUE TITLE
Free Malloc

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2133-PUC/2021-1#36]
Hola tengo la siguiente duda, si por ejemplo tenemos el siguiente pedazo de código:
en el cual en cada iteración se crea un nuevo puntero que en conjunto con malloc crea una nueva instancia de algún struct.

for (i=0, i < 5, i++) {
   struct Persona *puntero
   puntero = (struct Persona *)malloc(sizeof(struct Persona));
   ### SE TRRABAJA CON EL PUNTERO ###
   }

si luego para liberar el espacio de memoria realizo el comando:
free(puntero)
Entonces mi pregunta es si con esto se liberará la memoria de las 5 instancias puntero creadas, o solo de la última?
Por ende basta con hacer free(puntero) o tengo que guardar los punteros en alguna lista para luego liberar esa lista

**Comment by nmcin** [comment]
Hola,

En C las variables que declaras dentro de un scope se borran una vez que sales de este. 
- Si declaras la variable `puntero` dentro del for, no podrás usarla (ni hacerle free) fuera del for.
- Si haces `free(puntero)` dentro del for, se liberará la dirección de memoria apuntada por el puntero al momento de llamar a `free(puntero)`, es decir, en cada iteración reservarás memoria con malloc y la liberarás con free.

Espero haberte ayudado con eso, saludos!

**Comment by JuanDlugo** [comment]
Hola, 
Sii se entendió perfecto, Gracias.

Te hago entonces otra consulta que me surge con tu aclaración.

Si guardo en un puntero la última instancia de Persona que he creado hasta el momento al final de cada ciclo. 
Dentro del mismo for, pero en la siguiente iteración esta variable seguirá existiendo y guardando la dirección de memoria que le otorgue? 

Además, si relacionó 2 instancias entre ellas mediante punteros, cuando salga del for seguirán apuntando hacia lo ellas que fue lo que yo quise hacer verdad? porque si bien no puedo ocupar la variable como bien me dijiste, en esa dirección de memoria almacenada sigue existiendo la instancia que cree porque no la he liberado aún

**Comment by nmcin** [comment]
No estoy seguro de haberte entendido bien, pero trataré de responderte:

1. Las variables que declares dentro del ciclo se borran entre cada iteración. Si es una variable que declaraste antes del ciclo, lógicamente seguirá existiendo a lo largo de las iteraciones.
2. Si por relacionar instancias te refieres a guardar punteros dentro de un struct, al salir del for y si todas las instancias aún existen en memoria, entonces si seguiran apuntandose entre ellas.

Sin embargo, te recomiendo probar todas esas cosas por tu propia cuenta. Para eso puedes hacer un pequeño programa que implemente lo que quieres hacer, lo compilas y lo ejecutas, y si quieres lo puedes debuguear con valgrind para ver si tienes errores de memoria.

**Comment by JuanDlugo** [comment]
Ya perfecto, muchas gracias!
