### ISSUE TITLE
[Tarea 0] Duda Evento RECOVERED

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#37]
Hola! Mi pregunta es que en el enunciado se nos indica que a un paciente con estado **"sospecha en espera"** recibe un test positivo. Es necesario que nuestro programa revise antes de cambiar su estado a contagiado si es que realmente está en el estado "sospecha en espera" o debemos suponer que el **input será válido**?

En el caso que tengamos que revisar, cómo debemos señalar en el programa que no es válido el evento?

Gracias!

**Comment by inzuniga** [comment]
Hola! Si puedes asumir que el input siempre será válido.

Saludos!

**Comment by SebaHagedorn** [comment]
Muchas gracias!
