### ISSUE TITLE
[Tarea 0] Output de INFORM y STATISTICS.

### ISSUE THREAD

**Issue by nep0s** [IIC2133-PUC/2021-1#38]
Hola! En los ejemplos del enunciado, para estos dos eventos tenemos en la primera línea del output el código:

`1    INFORM 1 3`

`1    STATISTICS 1 3`

Que hacen referencia a los comandos que se reciben en el input, pero ¿es necesario imprimirlos también en la primera línea del output después de efectuado el evento?.

**Comment by rbhernandez** [comment]
Hola, sí, deben imprimirse en la primera línea tal como se muestra en el ejemplo de _output_.
Saludos!

**Comment by nep0s** [comment]
Gracias!
