### ISSUE TITLE
Error (Segmentation fault (core dumped)) al tratar de correr tarea

### ISSUE THREAD

**Issue by vsantelicest** [IIC2133-PUC/2021-1#40]
Hola!
Al tratar de correr la tarea con la línea indicada en el .pdf me sale el error:
Segmentation fault (core dumped)
Busqué en Google pero no sale nada útil sobre el origen del error, entonces quería saber si se trata de que algo está mal en el código de mi tarea nomas o es un problema mayor.
Gracias!

**Comment by vsantelicest** [comment]
Al correr el programa con `valgrind` me dice que no hay leaks: `ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)`. ¿Habrá otra manera de cachar que es lo que está mal?

**Comment by nmcin** [comment]
Dentro del output de `valgrind`, más arriba te debiera decir que se produjo un error, probablemente un `Invalid read` o `Invalid write` con el detalle del error.

**Comment by vsantelicest** [comment]
Tienes razón, me sale más arriba un error, pero no es del tipo que describes tú. El error es ` error calling PR_SET_PTRACER, vgdb might block`. ¿Alguna idea de que podría ser?

**Comment by CarloGauss33** [comment]
intenta con 
```
valgrind --leak-check=full
```
Con dicha flag, valgrind mostrara todos los errores y el trace. Con eso quizás puedas encontrar el error

**Comment by vsantelicest** [comment]
No me tira ningún error con esos comandos, solamente el que indiqué antes. Voy a preguntar por Discord para poder resolverlo :)

**Comment by RonaldoSosa** [comment]
Hola! Me tiro el mismo error y valgrind también me dijo lo mismo lo lograste solucionar?

**Comment by nmcin** [comment]
El error segmentation fault ocurre por mal manejo de memoria o punteros dentro de tu programa. El `error calling PR_SET_PTRACER, vgdb might block` no es relevante, no afecta a la ejecución del programa. Si tienes un segmentation fault y corres tu programa con valgrind, entonces este te dirá en que linea de tu código se produce el error y otros detalles.

Para correr tu programa con valgrind debes ejecutar:
```valgrind ./kevin-21 input.txt output.txt ```
o
```valgrind --leak-check=full ./kevin-21 input.txt output.txt ```

**Comment by felipeuribe99** [comment]
Hola, tengo el mismo problema. Valgrind no me tira errores y el output es el esperado, sin embargo, al correrlo como lo indican en las instrucciones me tira el mismo error de segmentation fault. Pudieron solucionarlo?
