### ISSUE TITLE
Apertura de archivo output file

### ISSUE THREAD

**Issue by jperalta2202** [IIC2133-PUC/2021-1#41]
Hola! en el archivo main.c de la tarea, se abre el archivo de output con el mode "w". Podemos cambiarlo al mode "a" si es que asi lo preferimos?

**Comment by nmcin** [comment]
Hola,

No se que esperas lograr con eso, pero tu programa debe crear el archivo de output desde cero. Si usas el modo "a" no vamos a poder corregir tu tarea correctamente, porque tus resultados dependerán de un archivo previo.

**Comment by jperalta2202** [comment]
Ok, gracias

**Comment by j4vito** [comment]
Entonces es posible usar el modo "a" si antes de eso creo el archivo desde 0?

**Comment by nmcin** [comment]
No pueden usar el modo "a". Aunque crees el archivo antes, al correr tu programa con distintos tests se irá acumulando el output y tendrás incorrectos los resultados de los tests.
