### ISSUE TITLE
Make

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2133-PUC/2021-1#44]
Hola, estoy intentando compilar mi programa con make en Ubuntu y me sale el siguiente error. 
No pude encontrar nada útil en internet asi que vine a pedir ayuda acá :)
La otra consulta que me surge con respecto a esto es que no entiendo cual es el objetivo de la carpeta obj,
Gracias de antemano.

![Captura de Pantalla 2021-03-31 a la(s) 11 32 28](https://user-images.githubusercontent.com/48494298/113162613-d4f92b80-9215-11eb-8a3e-ec92094833eb.png)

**Comment by fadediego** [comment]
Hola!
Es posible que tu directorio necesite permisos de administrador por alguna razón. Intenta ver si funciona corriendo "sudo make", o elimina dichos permisos especiales (hay harta información en google).
La carpeta obj tiene los archivos compilados, si no me equivoco. De todas formas, se crea al compilar los archivos.
Si el problema no es ese, podemos seguir buscando la solución.
Saludos!

**Comment by JuanDlugo** [comment]
Sii ahí con el sudo me funcionó! 
Buscaré en Internet para ver cómo elimino esos permisos especiales. 
Muchas Gracias!!
