### ISSUE TITLE
[Tarea 0] Tests

### ISSUE THREAD

**Issue by jgparot** [IIC2133-PUC/2021-1#45]
Hola! Hay alguna forma de comprobar que los output de los test están correctos?

**Comment by rbhernandez** [comment]
Hola, si quieres comparar archivos de output puedes usar el comando _diff_. Puedes buscar más información de cómo se ocupa :)
Saludos!

**Comment by jcechavarri** [comment]
Hola!

Puedes utilizar el comando `diff -b <archivo1> <archivo2>`, dónde archivo1 y archivo2 son las rutas a los dos archivos a comparar. Esto te muestra las diferencias entre ambos archivos, por lo que si no muestra nada tus archivos deberían ser iguales.

**Comment by jgparot** [comment]
Me refería a si hay un output esperado de los tests easy, medium y hard para revisar, o se debe comparar con los output de los test que funcionan también para Python. Igualmente muchas gracias por el comando, está muy útil.

**Comment by jcechavarri** [comment]
Vamos a subir los test más adelante, por mientras puedes intentar revisar "a mano" o crear tests en los que sepas la respuesta. Espero haber podido ayudarte!

**Comment by jgparot** [comment]
Si! Graciaas

**Comment by felipe-barria95** [comment]
Hola! En algunos tests mi archivo resultado.txt final difiere un poco en tamaño del archivo solution que ustedes subieron. Sin embargo cuando ejecuto `diff -b `me responde que esta todo ok. Me tengo que fijar solo en `diff -b` o algo más?

**Comment by nmcin** [comment]
Hola,

Basta con que `diff -b` no muestre diferencias.
