### ISSUE TITLE
[Tarea 0] README y gitignore

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2133-PUC/2021-1#46]
Tengo dos preguntas:
(1) ¿Debemos completar el README?
(2) ¿Qué debemos ignorar y qué no a la hora de subir la tarea?, ¿Debemos subir el archivo ya compilado nomás y todo el resto se ignora?

**Comment by mjretamales** [comment]
Hola! 
No debes completar el README, pero recuerda que debes entregar el informe en el buzón de Siding. 
Debes subir tu código al repositorio, el archivo de gitignore ya está en los repositorios. 
Saludos!

**Comment by jorge-ovalle** [comment]
Pero en el gitignore no se elimina la carpeta de python, solo el caché. Puedo modificar el gitignore tal que entregue solamente el código de la carpeta src y el compilado?

**Comment by nmcin** [comment]
No es necesario eliminar la carpeta con el código de python. Lo que debes entregar obligatoriamente es la carpeta `src` con el código en C dentro de la carpeta `kevin-21` y la `Makefile`, de manera que al ejecutar `make` en tu repositorio se compile tu programa.
Cualquier otra cosa da lo mismo si está o no en el repositorio (se razonable).

El informe se debe subir aparte a Siding.
