### ISSUE TITLE
duda en función fscanf en main

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#47]
Hola, en la función `fscanf` del módulo `main.py` dice "no es necesario que la reescriban" a qué se refieren con eso? no hay que escribirla en `C`?. Si sigo la lógica del `main.py` que ustedes nos entregaron y lo traspaso a `C`, tengo que ocupar la función `fscanf`?

**Comment by rbhernandez** [comment]
Hola, como puedes ver en el código base de C que les entregamos, la función _fscanf_ puede usarse directamente (es una función _built in_). Por esto se dice que no es necesario reescribirla. El cógido de la función _fscanf_ en python es para ayudarles a entender cómo funciona.

Saludos!
