### ISSUE TITLE
[Duda C] Duda input en C

### ISSUE THREAD

**Issue by Juampisaez** [IIC2133-PUC/2021-1#48]
Hola, sigo sin entender muy bien como se coloca el input en el codigo, como por ejemplo el del archivo txt. No se si me podrian orientar un poco, ya vi las capsulas de zoom.
Quedo atento :)

**Comment by CarloGauss33** [comment]
El proceso que ocurre es el siguiente:

tu función main tiene input de 2 variables que son entregadas según como se defina. 
```
int main(int argc, char** argv){return 0;}
```
argc es la cantidad de argumentos que el ejecutable espera y argv es un array de tamaño argc que contiene el input de dicho ejecutable. Por ejemplo

```
myprograma input.txt output1.txt output2.txt imagen1.png
```

En este caso argc es igual a 6, (5 que son entregados por el usuario y el ejecutable por si mismo)
mientras que argv contiene punteros a *streams de caracteres*, por ejemplo myprograma  seria el stream de caracteres asociado a argv[0].

Luego, en caso de ser archivos y no solo texto, estos archivos se abren utilizando la libreria estandar *stdio*, por ejemplo
```
FILE* input_stream = fopen(argv[1], "r");
```
Donde se le indica a C que lea el archivo *input.txt*. Y esa lectura sea asignada a un stream de tipo FILE*
Despues, con dicho stream cada vez que uses la funcion ```fscanf(input_stream, formato, address);``` 
C leera dicho stream y asignara los valores correspondientes

Sobre *fscanf*, si tu archivo es por ejemplo una secuencia de numeros "1 2 3 4"
entonces cada vez que uses ```fscanf(input_stream, "%d %d", &myint1, &myint2);```  la funcion tratara de leer 2 enteros que han de estar separados por un espacio. y el input stream ahora sera igual a " 3 4", asi permitiendo continuar la lectura de dicho archivo
