### ISSUE TITLE
[TAREA 0] Duda casos CORRECT

### ISSUE THREAD

**Issue by tedroppelmann** [IIC2133-PUC/2021-1#49]
Hola. ¿Podemos asumir que no habrán intercambios de nodos hijos entre nodos si es que uno de los nodos no tiene hijos? Es decir, cambiar todos los contactos estrechos (nodos hijos) de algún nodo a otro nodo que antes no tenía hijos.
Saludos!

**Comment by nmcin** [comment]
Hola,

Si te refieres al evento `CORRECT`, no puedes aumir que ambos tengan necesariamente contactos estrechos (nodos hijos), podría darse el caso de que uno no tenga hijos.
