### ISSUE TITLE
[Duda Tarea 0] Duda input tests y evento CORRECT

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#50]
Hola! Ya probé los tests Easy con mi programa y salen correctos. Al correr los tests Medium me tira error de segmento y esto me dice Valgrind: 
==70678== Invalid read of size 8
==70678==    at 0x1093D3: search_contact (person.c:53)
==70678==    by 0x1096CB: search (world.c:41)
==70678==    by 0x109CE2: correct (world.c:181)
==70678==    by 0x10AC6B: main (main.c:192)
==70678==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==70678== 
==70678== 
==70678== Process terminating with default action of signal 11 (SIGSEGV)
==70678==  Access not within mapped region at address 0x10
==70678==    at 0x1093D3: search_contact (person.c:53)
==70678==    by 0x1096CB: search (world.c:41)
==70678==    by 0x109CE2: correct (world.c:181)
==70678==    by 0x10AC6B: main (main.c:192)
Lo raro es que todos los otros tests funciona bien el evento CORRECT, pero en estos tests al parecer no encuentra las personas que debo buscar.

Por lo que me surgió la duda si es posible que en los tests nos entreguen eventos inválidos con personas que no existan o está malo mi programa?

Gracias!

**Comment by CarloGauss33** [comment]
Lo que puede estar pasando es que creaste un array de un tamaño _**n**_  pero luego iteras segun otro valor que es mayor a tal. En los casos easy puede que no de _SEGFAULT_ debido a que los tamaños son mucho mas pequeños.

Te recomiendo checkear con todos los test, para así saber desde que punto se empieza a caer el programa, y con eso puedes determinar mas o menos cual de todos los inputs es el que afecta el funcionamiento

**Comment by PDominguezW** [comment]
Me pasa lo mismo, pero revisando mi código me di cuenta que no cree ningún array como dice @CarloGauss33 . De hecho, revisando en que comando se cae mi programa para cada input, me di cuenta que el error siempre ocurre muy cercano a la linea x . ¿Es posible que no se me este entregando mas memoria y por eso el programa se cae?

**Comment by isiguelfand** [comment]
Hola! Yo tengo el mismo problema! Me pasa dentro del CORRECT. Sé que estoy iterando mal (como si la ruta fuera más profunda) pero no me queda claro porque, por si a alguno le sirve.

**Comment by chineseJack564** [comment]
Hola,
probablemente por 2 razones:

- Estas intercambiando una persona con hijo con otra person sin hijo, produciendo errores de puntero
- En un proceso anterior como negative, eliminaste un hijo de manera equivocada sin haber hecho cambio en el padre.

Como recomendacion, hay una herramienta de dubug mas detallada llamada gdb!

**Comment by SebaHagedorn** [comment]
Hola! Estoy revisando los posibles casos de error, gracias por las respuestas!

**Comment by EduardoIllanes** [comment]
Hola! Estoy enfrentando el mismo problema, que era lo que te producía error al final?
