### ISSUE TITLE
Duda Correct y sus argumentos en main

### ISSUE THREAD

**Issue by milosoria** [IIC2133-PUC/2021-1#51]
Hola! Según el enunciado CORRECT recibe country(int) region(int) person route 1 person route 2, mi duda es en qué parte del llamado de CORRECT se encuentran las definiciones de person_route1 y de person_route2: 
```else if (string_equals(command, "CORRECT"))
    {
      fscanf(input_file, "%d", &depth);
      printf("CORRECT %d %d %d ", country_id, region_id, depth);
      /* Obtenemos la primera ruta desde el archivo*/
      for (int r = 0; r < depth; r++)
      {
        fscanf(input_file, "%d", &contact_id);
        printf("%d ", contact_id);
      }
      /* Obtenemos la segunda ruta desde el archivo*/
      fscanf(input_file, "%d", &depth);
      printf("%d ", depth);
      for (int r = 0; r < depth; r++)
      {
        fscanf(input_file, "%d", &contact_id);
        printf("%d ", contact_id);
      }
      printf("\n");

      /* [Por implementar] correct */
}```

**Comment by nmcin** [comment]
Hola,

No se si entendí tu duda pero, como describen los comentarios, dentro del primer `for` se obtiene person_route1 y en el segundo `for` se obtiene person_route2. Es parte de la tarea que tu decidas como usar eso para ejecutar el evento CORRECT.
