### ISSUE TITLE
[Tarea 0] Duda valgrind

### ISSUE THREAD

**Issue by catalinamusalem** [IIC2133-PUC/2021-1#52]
Hola! cuando ejecuto valgrind sin haber cambiado nada del archivo main.c original me aparece el siguiente error

![image](https://user-images.githubusercontent.com/61999358/113361384-43c3ab00-9322-11eb-8949-e6dfe39e90ed.png)
Es normal que salga?
Gracias!

**Comment by nmcin** [comment]
Hola,

Eso pasa porque le estas dando un input inválido (o acaso existe input.txt?). Prueba dandole alguno de los test que te entregamos de input.
```valgind ./kevin-21 tests/test.txt output.txt```

**Comment by catalinamusalem** [comment]
Gracias!

**Comment by chineseJack564** [comment]
Para que te sale todos los errores en detalle puedes usar 
`valgind -v --leak-check = full ./kevin-21 tests/test.txt output.txt`
Tambien esta la opcion de usar gdb para un debug mas especifico! Puedes buscar tutorial en google!
