### ISSUE TITLE
[Duda C] Error con include en VScode

### ISSUE THREAD

**Issue by Fernan-tess** [IIC2133-PUC/2021-1#53]
Hola, 

Al momento de ejecutar make, vs me arroja error en el #include, traté de seguir los pasos recomendados usando vspkg pero no sirvió 

![image](https://user-images.githubusercontent.com/53883016/113387706-3aa6fe00-9363-11eb-9f7b-9e43f3d3fd15.png)

**Comment by benjastraub** [comment]
A mi me pasó lo mismo. Si haces botón derecho en la ampolleta se despliega un menú de opciones. Debería aparecer una que es como add to include PATH. A mi me funcionó haciendo click en esa.
