### ISSUE TITLE
Complejidad de búsqueda de un paciente 0

### ISSUE THREAD

**Issue by Tngarrido** [IIC2133-PUC/2021-1#55]
Hola, para el análisis de esta complejidad, debemos suponer que la búsqueda consiste en nos entreguen un Id de la persona y dado eso, es que debemos buscarla en nuestra estructura ? o simplemente se refiere a que nos entregan el pais_ID y la región_ID en la cuál vive el paciente 0 ?? Gracias de antemano. adjunto el enunciado:
![image](https://user-images.githubusercontent.com/42189869/113429613-d017b180-93a6-11eb-8e8d-7bdbac712ccd.png)

**Comment by nmcin** [comment]
Hola,

Se refiere a encontrar a un paciente cero a partir del pais_id y region_id.
