### ISSUE TITLE
[Duda C] Error "expected identifier..."

### ISSUE THREAD

**Issue by milosoria** [IIC2133-PUC/2021-1#56]
Hola, declarando la estructura person en mi archivo person.h me aparece el siguiente error: expected identifier or ‘(’ before ‘{’ token Person. La declaracion del struct sigue la siguiente forma: 
```
struct person;
typedef struct person Person;
Person {
    int y;
    int x;
    Person* atributo_x;
    Person* atributo_y;
    Person* atributo_z;
    etc;
};
```
Antes de eso solo tengo la linea `#include <stdio.h>`. No estoy seguro como arreglar el error.

**Comment by TrinidadVargas** [comment]
Hola! Tienes algunos errores de sintaxis
El nombre de tu struct es ```struct person```,  ```Person```solo sirve para declararlo adentro de la estructura o en una función del programa, pero no para definir la estructura

Entonces este código debería funcionar bien
```c
typedef struct person Person;
struct person 
{
    int y;
    int x;
    Person* atributo_x;
    Person* atributo_y;
    Person* atributo_z;
};```
