### ISSUE TITLE
[Tareo 0] Duda sobre calculo de complejidad en el informe

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#57]
Hola,
En el enunciado nos pide calcular la complejidad de todas las funciones, eso es decir desde Add_Contacts hasta Statistics, las 7 funciones, y otra duda respecto esque tenemos que calcular matematicamente o podemos dar una justificacion verbalmente y asi sacar la complejidad?

Tambien tengo una duda respecto al calculo de complejidad de la busqueda de paciente 0, esa complejido tambien debe depender de cantidad de Personas en el arbol? O depende de cantidad de paises y regiones?

**Comment by jcechavarri** [comment]
Hola!
Si, se pide la complejidad de las funciones que mencionas. No es necesario calcular la complejidad matemáticamente, basta con que des una idea general para justificar la complejidad. Por ejemplo, puedes decir que si tienes un for sería O(n). Lo importante es que respaldes correctamente la complejidad de tu implementación.

Con respecto a tu última duda, la idea es que tu veas de qué depende, pero puedes mencionarla en relación a la cantidad de personas y si quieres también agregar la complejidad en relación a la cantidad de países y regiones.
