### ISSUE TITLE
[Duda C] Make multiple definition

### ISSUE THREAD

**Issue by PDominguezW** [IIC2133-PUC/2021-1#58]
Cuando intento ejecutar el make, me imprimer el error 'multiple definition of `<funcion>'' para cada funcion.

**Comment by CarloGauss33** [comment]
Hola! Fijate en que los .h solo declares las funciones sin el {} al final, osea 
```
typo myfuncion(args);
```
Ademas, también puede ser que definiste 2 funciones con el mismo nombre en archivos separados, C no permite esto. O también otro caso es que estas redefiniendo el int main() en algún otro archivo que no es el principal.

Si es que ninguno de estos es el caso, te recomiendo ir al Discord para poder ver a detalle tu problema
