### ISSUE TITLE
error: expected declaration specifiers or ‘...’ before string constant

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#60]
Hola, cree un módulo para probar ciertas cosas de C, pero cada vez que intento hacer algo me sale el mismo error; **expected declaration specifiers or ‘...’ before string constant**
Por ejemplo intento hacer esto; 
![image](https://user-images.githubusercontent.com/59337116/113484319-14c24c00-947e-11eb-9e32-68aa4a28efd0.png)
y me responde con esto;
![image](https://user-images.githubusercontent.com/59337116/113484329-20ae0e00-947e-11eb-8960-b2244343ab89.png)
No entiendo cuál es el error, si me pueden ayudar por favor ..

**Comment by nmcin** [comment]
Hola,

Probablemente tu error este en alguna linea anterior a esa, donde se te pudo haber olvidado un `;`, cerrar algún parentesis o algún otro error de sintaxis. Revisa si es algo de eso.

**Comment by Camila-sty** [comment]
No tengo nada más que eso...

**Comment by nmcin** [comment]
Para poder usar `printf` debes incluir la librería de IO, con ```#include <stdio.h>```
Además, tu código debe ir dentro de una función para ser compilado. Especificamente dentro de la función `main` para ser ejecutable.
Lo mínimo que debes tener para ejecutar esa linea sería:
```
#include <stdio.h>

int main() {
  printf(...);
}
```
Luego para compilarlo en un ejecutable:
```gcc archivo.c -o ejecutable```

**Comment by Camila-sty** [comment]
Ok, en este caso debería ejecutar `gcc p.c -o main` ? y donde sale la respuesta? en la misma consola ? porque no me sale nada

**Comment by nmcin** [comment]
Si, compilas con `gcc p.c -o main` y luego ejecutas el programa con `./main`.

Te pedimos eso si que revises el material disponible antes de hacer issues. En el curso de intro a C que puedes encontar en el README del repositorio del curso esta todo esto muy bien explicado.

**Comment by Camila-sty** [comment]
Gracias, sí he visto el material mas las ayudantías.. pero no entendí, me anduve enredando.. en nuevo para mi este lenguaje. 
Gracias, sorry la pregunta básica.
