### ISSUE TITLE
[Tarea 0] Outputs de Ejemplo

### ISSUE THREAD

**Issue by j4vito** [IIC2133-PUC/2021-1#61]
Hola! Estaba probando mi programa con los test Medium y me encontré con lo siguiente:
En los inform de la solución esperada hay varias personas positivas que no son paciente zero ni fueron objetivo de un comando POSITIVE.
Por ejemplo en el input Medium/test1_txt no se encuentra [POSITIVE 1 0 3 1 15 251] sin embargo en el output esperado del test medium 1, en un (inform 1 0) (en la línea 768) aparece la persona con la ruta recién señalada(1 0 3 1 15 251 ) con estado 2 (POSITIVO). Entonces es posible que hayan errores en los output entregados para probar? o hay alguna otra forma de que una persona sea positiva además de positive y ser paciente cero? 

![image](https://user-images.githubusercontent.com/62030403/113493950-743e4d00-94ba-11eb-95a0-d6445d54044d.png)
![image](https://user-images.githubusercontent.com/62030403/113493965-91731b80-94ba-11eb-97f4-da3315418e56.png)

**Comment by mariovaldesa** [comment]
En la línea 783 de ese test muestran cuando se contagia el 251 y después por un CORRECT cambia la ruta en la que está la persona.
(no soy ayudante)
