### ISSUE TITLE
[Duda C] Error uninitialised value of size 8

### ISSUE THREAD

**Issue by Juampisaez** [IIC2133-PUC/2021-1#63]
Hola, estoy pegado desde la mañana tratando de solucionar este error.
![image](https://user-images.githubusercontent.com/48323752/113494800-3b09db00-94c2-11eb-8ee4-86b90b37e06d.png)

Si alguien me puede echar una mano se lo agradeceria, he buscado en internet y no logro solucionar el problema.
Desde ya, muchas gracias :)

**Comment by mpbascunan** [comment]
Me pasaba lo mismo y era porque en un momento en search_contact retornaba NULL, lo que hacía que al entrar nuevamente a search_contact le pasara un puntero NULL. Igual es bien específico, no se si te sirva.

**Comment by tomahawk99** [comment]
Hola, soy un alumno también, y me paso algo parecido. Me pasaba que sobre-declaraba una variable en un loop, lo que me tiraba el mismo error. Igualmente es super específico y ese mensaje de error puede significar una u otra cosa. Intentaste usar --track-origins=yes?
