### ISSUE TITLE
Uso de comando "cmp" para ver diferencias entre archivos

### ISSUE THREAD

**Issue by Tngarrido** [IIC2133-PUC/2021-1#65]
Hola! estoy utilizando el comando "cmp" para comparar mis output con las soluciones, los test Easy no arrojaron ninguna diferencia, sin embargo, desde el test_1 de los tests Medium hasta el final de los tests Hard me arroja la siguiente diferencia en la línea 1 en todos los otros archivos:
![image](https://user-images.githubusercontent.com/42189869/113511124-3a0d9380-952c-11eb-92e6-6288b0b6bdaf.png)
![image](https://user-images.githubusercontent.com/42189869/113511376-7b527300-952d-11eb-9d8b-f3b133bec2ef.png)

Pero si yo abro mi archivo solución test_1 y mi archivo out_1, se ven visualmente iguales (incluso tienen las mismas cantidades del carácter espacio en cada línea).
![image](https://user-images.githubusercontent.com/42189869/113511219-c3bd6100-952c-11eb-8295-323b745819fa.png)
No se si me podrían ayudar a identificar el posible diferencia o a buscar información que me pueda ayudar. También me gustaría saber si la manera en que revisarán la correctitud de los archivos serán a través de este comando "cmp". Gracias de antemano, saludos!!

**Comment by RonaldoSosa** [comment]
Hola! No soy ayudante pero por discord un ayudante dijo que el comando para comparar los archivos es diff -b file_1.txt file_2.txt, dijeron que se corriera desde la consola de ubuntu y si no te imprime nada significa que esta bueno, el flag -b es importante ya que parece que ignora los espacios extra y cosas de ese estilo, también arregla cosas del formato (a veces puedes tener 2 archivos iguales y uno pesa más que el otro y -b arregla esas cosas)

**Comment by Tngarrido** [comment]
Gracias !! @RonaldoSosa con "diff -b" no me arroja nada. Supongo que con este comando será revisado la correctitud del código
