### ISSUE TITLE
[Tarea 0] Prints en eventos

### ISSUE THREAD

**Issue by ignacio-urrutia** [IIC2133-PUC/2021-1#66]
Hola, quería saber si es necesario imprimir las instrucciones del código tal como viene hecho en el archivo main.c. Hice la comparación de tiempo con y sin los prints y mi código pasa de demorarse alrededor de los 10 segundos con prints a 0.4 s sin ellos. En el enunciado no está especificado que sea necesario y por esto surge mi duda. 

Saludos

**Comment by rbhernandez** [comment]
Hola! no es necesario. De hecho, el programa sí es más lento con los _prints_, por lo que lo mejor sería no tenerlos.
#34 

Saludos
