### ISSUE TITLE
find: ‘src/structs’: No such file or directory

### ISSUE THREAD

**Issue by Camila-sty** [IIC2133-PUC/2021-1#67]
Hola cuando quiero compilar me sale algo que no entiendo qué significa ... 
![image](https://user-images.githubusercontent.com/59337116/113516598-1ad12f00-9549-11eb-8ef2-8cc7dbff721c.png)
 Dentro de `src `no tengo ningún archivo que se llame `structs`, pero si tengo archivos `.h ` donde ocupo `structs`.
Es un error lo que me sale? o debo ignorarlo?

**Comment by nmcin** [comment]
Hola,

La `Makefile` que les pasamos busca archivos en la carpeta `src/structs`, algo que puede ser usado como convención en algunos casos. Como esa carpeta no existe se ve ese warning, sin embargo, no es necesario que hagas nada y puedes ignorarlo.

**Comment by Camila-sty** [comment]
Gracias!
