### ISSUE TITLE
[Tarea 0] Complejidades

### ISSUE THREAD

**Issue by jorge-ovalle** [IIC2133-PUC/2021-1#68]
Calculo la complejidad en el peor caso? Porque en la mayoría de los eventos también dependerá de la ruta de la persona que se ingresa. En cuanto a la complejidad de búsqueda del paciente cero, considero los índices nomás?

**Comment by jcechavarri** [comment]
Hola!
Efectivamente, se pide la complejidad en notación O (el peor caso). En cuanto a tu segunda pregunta, la idea es que analices la función y menciones de qué depende y cuál sería la complejidad de encontrarlo.
Espero haberte ayudado 😄

**Comment by jorge-ovalle** [comment]
> Hola!
> Efectivamente, se pide la complejidad en notación O (el peor caso). En cuanto a tu segunda pregunta, la idea es que analices la función y menciones de qué depende y cuál sería la complejidad de encontrarlo.
> Espero haberte ayudado 😄

Y considero la complejidad en memoria?

**Comment by jcechavarri** [comment]
> > Hola!
> > Efectivamente, se pide la complejidad en notación O (el peor caso). En cuanto a tu segunda pregunta, la idea es que analices la función y menciones de qué depende y cuál sería la complejidad de encontrarlo.
> > Espero haberte ayudado 😄
> 
> Y considero la complejidad en memoria?

No, no es necesario que menciones la complejidad en memoria
