### ISSUE TITLE
[Tarea 0] Uso de módulos y make

### ISSUE THREAD

**Issue by fmitjans** [IIC2133-PUC/2021-1#69]
Hola! ¿Puedo usar los módulos de la ayudantía 1: `linked_list.c` y `linked_list.h`  en mi tarea?
¿Si los importo afecta a la eficiencia de mi programa?
¿Para poder usarlos en mi tarea puedo dejar el `Makefile` como está?

**Comment by nmcin** [comment]
Hola,

Si crees que te van a ser útiles si puedes usarlos. No es necesario cambiar la Makefile si guardas los archivos dentro de la misma carpeta que tu código.
