### ISSUE TITLE
Link a headers

### ISSUE THREAD

**Issue by ctronp** [IIC2133-PUC/2021-1#7]
como hago un link a un header pre-compilado, osea en formato ```.o```

hasta ahora me retorna este error:
```shell
*.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```

**Comment by CarloGauss33** [comment]
@ctronp En general el error 
``` sh
*.o: file not recognized: file format not recognized
```
Se refiere a que algo fallo mientras se compilaba el archivo, si es que el error te ocurrió mientras usabas un make, intenta recompilar los archivos con
```sh
make clean
make
```
Si es que solo deseas compilar múltiples archivos hacia uno común, la estructura común con gcc es la siguiente

```
gcc file1.c file2.c -o nombredelprograma
```

**Comment by ctronp** [comment]
Gracias
