### ISSUE TITLE
[Tarea 0] Formato informe

### ISSUE THREAD

**Issue by MGilB** [IIC2133-PUC/2021-1#71]
Hola, tengo una duda si para el informe se pide un formato en especifico escrito como LaTex o como nosotros queramos mientras el formato final sea pdf?

**Comment by jcechavarri** [comment]
Hola!
Mientras el formato final sea pdf y no esté escrito a mano todo bien. Si quieres agregar gráficos o imágenes pueden ser fotos adjuntas, pero el informe tiene que estar escrito en computador.
