### ISSUE TITLE
[Tarea 0] Cálculo de complejidad con malloc/calloc

### ISSUE THREAD

**Issue by mpbascunan** [IIC2133-PUC/2021-1#72]
Hola, mi duda es si cuando pongo malloc() o calloc() eso es O(1), o depende de la cantidad de memoria que pidamos?

**Comment by rbhernandez** [comment]
Hola!
Para el análisis de la tarea se pide la complejidad respecto a la cantidad de _Personas_, por lo que si en algún método haces uso de _calloc_ o _malloc_ como mencionas, debes preocuparte de la cantidad de veces que lo haces (siempre que se relacione con la cantidad de personas) y no de la memoria que utilizas. Esta es necesaria cuando se hace un analisis de complejidad sobre la memoria adicional.

Saludos!
