### ISSUE TITLE
[Tarea 0] Utilización de Valgrind con la Makefile

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#73]
Hola! hay alguna opción para modificar la makefile para poder correr valgrind, o tenemos que correr valgrind manualmente?

**Comment by nmcin** [comment]
Tecnicamente se puede, pero tendrás que averiguar por tu cuenta si quieres hacerlo. En este [link](https://makefiletutorial.com/) encontrarás todo tipo de información sobre como usar la Makefile.

**Comment by SebaHagedorn** [comment]
Vale, gracias
