### ISSUE TITLE
[Tarea 0] Error al hacer make

### ISSUE THREAD

**Issue by jorgemayol** [IIC2133-PUC/2021-1#74]
Tengo un error que me aparece cuando hago make y este aparece cuando hago #include "person.c" en world.c y si no lo incluyo no aparece, el error es:
![image](https://user-images.githubusercontent.com/48481802/113636566-c8733980-9640-11eb-92ff-321782912154.png)

**Comment by nmcin** [comment]
Hola,

Cuando importas archivos debes siempre importar los header y no las definiciones de código. Es decir, desde tu `world.c` deberías importar `person.h`.

**Comment by jorgemayol** [comment]
Entonces si quiero importar person a world.c solo debo incluir el archivo person.h y no el person.c?

**Comment by nmcin** [comment]
Efectivamente. También debes incluir a `person.h` en `person.c`.

**Comment by jorgemayol** [comment]
@nmcin muchas gracias!!!
