### ISSUE TITLE
[Tarea 0] Casos especiales

### ISSUE THREAD

**Issue by Afro27** [IIC2133-PUC/2021-1#75]
Quería saber si es posible que en el caso de NEGATIVE, se pida declarar como negativo a la raíz de un árbol(nodo 0). Por otro lado,  si se podría dar el caso de que se haga CORRECT done uno o ambos nodos, no tenga entidades hijas o descendientes. Muchas gracias.

**Comment by lucas-valenzuela** [comment]
NEGATIVE: Debido a que el caso cero parte como contagiado, nunca podría eliminarse.
CORRECT: No sé si entendí bien tu pregunta, pero el enunciado aclara que de los dos nodos a los cuales se les aplica el correct, uno no puede ser descendiente del otro.

**Comment by Afro27** [comment]
Respecto al correct me refiero por ejemplo a cambiar los hijos de los nodos 3 y 7. Donde los hijos de cada uno son:
3->{8,9}
7->{} (no tiene hijos)
Estos casos pueden suceder? La respuesta deberia quedar como:
3->{}
7->{8,9}

**Comment by jcechavarri** [comment]
Hola!

Esto se respondió en la issue #49 

Si tienes cualquier otra duda escribe nomas!
