### ISSUE TITLE
[Tarea 0] Output debe ser literal??

### ISSUE THREAD

**Issue by Baelfire18** [IIC2133-PUC/2021-1#76]
![image](https://user-images.githubusercontent.com/50716449/113642658-57d31980-964e-11eb-8549-ed5c032fad1e.png)
Hola, al correr el main.c y main.py obtengo una sutil diferencia en los outputs, importa? Se comparará solo el texto literal?

**Comment by jcechavarri** [comment]
Hola!
Las tareas se corrigen automáticamente, por lo que una diferencia de un espacio te puede arrojar error.
Saludos!

**Comment by Baelfire18** [comment]
Gracias!
