### ISSUE TITLE
[Duda C] Problema con tiempo de ejecucion

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#77]
Hola, tengo un problema con el tiempo de ejecucion de codigos de C, en 2 computadores distintos me dan resultados muy diferentes.
en un computador me da un tiempo de esta forma.
![image](https://user-images.githubusercontent.com/69604944/113644139-0c226f00-9652-11eb-85d4-044f6c9ba212.png)
y en otro computador
![image](https://user-images.githubusercontent.com/69604944/113644389-a5518580-9652-11eb-93bc-9ce2bcda9c5d.png)

Si se fija hay una gran diferencia, y en computador 1 el real es mucho mas que sys+user.
Sin embargo en ambos computadores el tiempo de ejecucion de python es casi lo mismo.
He estado investigando pero no encuentro la explicacion, entonces ahora no se que hacer para el informe.

**Comment by fadediego** [comment]
Hola!

En ocasiones tener muchos programas andando en el PC puede generar que tome más tiempo de ejecución. Intenta ver si al reiniciar el computador baja/sube el tiempo de ejecución. De todas formas, es normal que varíe el tiempo de ejecución.
Para tu informe, escoge alguno de los computadores (ojalá el propio) y corre el programa con C y Python en dicho computador. Justifica las razones de por qué dan distintos los tiempos de ejecución entre los distintos lenguajes. Puede que los resultados no sean los que esperes, pero mientras justifiques el por qué entonces está bien.

Saludos!

**Comment by chineseJack564** [comment]
Hola a todos,
Dps de 3 horas encontre la solucion a este problema. Probablemente es porque tiene el workplace en windows, si este es el caso, le van a parecer una ventana asi al entrar VScode:
![image](https://user-images.githubusercontent.com/69604944/113748711-d378a900-96d6-11eb-8019-205f5d43a677.png)
El problema con esto esque vas a abrir un archivo en un carpeta que esta en windows desde un programa que se encuentra en C, aumentando el tiempo de I/O, que es la lectura a tu disco.
Para resolver esto tienen que mover su workspace a linux,siguiendo los siguientes pasos:
`\wsl$\Ubuntu-18.04\home\<user name>
`
y tiene que pegar su workplace en esta carpeta, luego abrirlo en wsl, ahora no les van a parecer la ventanita.
Ahora le damos acceso a wsl con el siguiente condigo
`chmod u+x .\kevin-21`

ahora ejecuta tu programa con el comando tiempo y wuala:
![image](https://user-images.githubusercontent.com/69604944/113749369-98c34080-96d7-11eb-9442-e2b8a725e24a.png)
 A mi personalmente me reducio 25s.
Espero que les sirvan!

**Comment by fadediego** [comment]
Bueno, también puede ser eso 😅.
Gracias por la info!!
