### ISSUE TITLE
[Tarea 0] Informe comparar C vs Python

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2133-PUC/2021-1#78]
Hola! Tengo una duda respecto a esta parte del informe nos dice que comparemos las velocidades de ejecución al usar los test que nos enviaron, en el informe además de los resultados que nos entregaron deben ir además de una explicación del por qué uno es más rápido que el otro o basta con mostrar los resultados?

**Comment by nmcin** [comment]
Hola,

Se espera que des una breve justificación de porque ocurren las diferencias
