### ISSUE TITLE
[Tarea 0] Duda Informe Estructuración de Árbol con Arreglos

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2133-PUC/2021-1#79]
Entiendo que tenemos que calcular la complejidad de los algoritmos indicados en el caso en que se reemplacen las listas ligadas con arreglos en la estructuración del árbol. Sin embargo mi duda es en específico con el caso de inserción. Esta duda me nace ya que se nos pide que calculemos la complejidad para la inserción, sin embargo no se me ocurre ningún momento en la tarea en el que hayamos tenido que insertar una persona en una lista ligada.
Para este algoritmo, ¿hablamos del tema general de insertar un elemento en un arreglo versus insertarlo en una lista? Entonces qué hacemos con los casos de búsqueda y eliminación, ¿utilizamos el algoritmo usado en la tarea? ¿O también hablamos de un caso general?

**Comment by nmcin** [comment]
Hola,

Debes hacer la comparación con respecto a los eventos de la tarea. La inserción se refiere a agregar personas al arbol, no necesariamente dentro de la lista o del arreglo. Lo mismo para los casos de búsqueda y eliminación.
