### ISSUE TITLE
[Tarea 0] Duda errores valgrind

### ISSUE THREAD

**Issue by Afro27** [IIC2133-PUC/2021-1#80]
![image](https://user-images.githubusercontent.com/53800902/113667901-73a2e380-967f-11eb-86fb-9df5027609eb.png)
Este tipo de errores son a los que se refiere el enunciado con "errores de memoria"? Tengo entendido que el error es por no aprovechar todo el espacio de un malloc "Address 0x4a4ed28 is 24 bytes inside a block of size 48 free'd". Pero en si no afectan en nada al programa fuera de "desperdiciar" un poco de espacio ya que todos los tests me salen correctos. Gracias.

**Comment by nmcin** [comment]
Hola,

Ese error significa que estas leyendo un espacio de memoria que ya fue liberado (ya le hiciste free). El bloque al que le hiciste free era de 48 bytes y tu estas leyendo los bytes 24 a 30 (24+8).
