### ISSUE TITLE
[Duda C] Error sin valgrind, pero sin error con valgrind

### ISSUE THREAD

**Issue by Juampisaez** [IIC2133-PUC/2021-1#81]
Hola, estaba corriendo mi codigo con valgrind, y funciona a la perfección (haciendo los frees() y dejandolos en 0). Sin embargo, si luego corro mi programa sin valgrind, este me lanza un segment error, algo que no me aparece usando valgrind por lo que no puede detectar el error en particiular.

Quedo atento, muchas gracias!

**Comment by nmcin** [comment]
Hola,

Estás corriendo el programa con los mismos argumentos (input) ?

**Comment by Juampisaez** [comment]
Sii, eso no cambia, es muy extraño
Creo que lo solucione pero no estoy muy seguro. No se si podrias corroborarlo con tu PC? ya lo subi a mi repo

**Comment by nmcin** [comment]
Pude correr varios test y no tuve ningún error sin valgrind

**Comment by Juampisaez** [comment]
Gracias!

**Comment by Benjale** [comment]
@Juampisaez Como lo solucionaste?

**Comment by Juampisaez** [comment]
@Benjale lo que hice fue ver solamente en que evento se caia el programa y tratar de darle una interpretacion a lo que estuviese ocurriendo. En mi caso fue que hacia un malloc en vez de ocupar la funcion init.
