### ISSUE TITLE
[Duda Complejidad insertion sort]

### ISSUE THREAD

**Issue by mariovaldesa** [IIC2133-PUC/2021-1#82]
Hola, tengo una duda de la complejidad de insertion sort vista en clases. Cuando partimos viendo insertion sort dijeron que la complejidad de solamente insertar era O(n) y después cuando vimos el pseudo código que corrige las inversiones dijeron que en promedio su complejidad era O(n^2). Mi pregunta es si en ese O(n^2) está considerada la complejidad de insertar. Gracias.

**Comment by yadran** [comment]
Sí, claro.  Está considerada.
El algoritmo tiene que insertar cada uno de los n elementos.
--Yadran
