### ISSUE TITLE
[Duda C] Problema guardando Nodos hijos en Memoria

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2133-PUC/2021-1#83]
Tengo el siguiente problema, 
En mi programa cuando voy poblando mi árbol con nodos y punteros a estos nodos todo funciona perfecto. El problema es que luego cuando intento recorrer mi árbol es como que los datos no se guardaron. Es decir mis punteros head y next no guardan la info.
Me costo mucho pero encontré una solución al problema y quiero entenderla porque la verdad no lo entiendo.
Denominemos por ejemplo al caso cero de mi árbol como "caso_0" al cual accedo de la siguiente manera:
![Captura de Pantalla 2021-04-06 a la(s) 11 48 30](https://user-images.githubusercontent.com/48494298/113739717-0d917d00-96ce-11eb-8834-4048703f268f.png)

Luego al terminar de generar todos los contactos para agregar los debo guardar y lo hago guardando la dirección de memoria de la lista de contactos nuevos en el head del caso_0.
El tema es que si lo guardo como en la primera linea de la foto a continuación, los datos no se guardan. En cambio si lo realizo como en la linea 2 si funciona. Aparentemente hay que entregar todo el camino real del árbol hasta el nodo objetivo
Pero esto no solo es poco práctico sigo que aumenta la complejidad a medida que aumenta la profundidad.

![Captura de Pantalla 2021-04-06 a la(s) 11 53 11](https://user-images.githubusercontent.com/48494298/113740860-1767b000-96cf-11eb-8eda-53f6784402fe.png)

La linea 3 me termina por printear el id 1 esperado, mientras que la linea 4 me tira error porque el head retorna (Nil).
Porfavor si alguien me explica el porque guardar la dirección de memoria en mi variable de ayuda "objetivo o caso_0" no es lo mismo que guardarla en la dirección real del nodo siendo que ambos tienen la misma dirección de memoria.

**Comment by fadediego** [comment]
Hola!
¿Puedes subir tu código a Github, para visualizarlo más detenidamente? Debe ser una confusión con los punteros. Sin embargo, para evitar mostrar código, es mejor que hablemos por el Discord. Si sale algo de uso general lo posteo acá.
Saludos!

**Comment by JuanDlugo** [comment]
Listo! Gracias
