### ISSUE TITLE
[Tarea 0]

### ISSUE THREAD

**Issue by FdoTorres1** [IIC2133-PUC/2021-1#84]
Hola! Llevo un tiempo trabajando con un `Segmentation fault: 11 `, lo había ignorado porque no había significado un problema en el desarrollo de mi tarea pero ahora que necesito imprimir más cosas en la consola no las imprime. Incluso con el el `.txt` que viene, pongo un print para ver que entre en el `INFORM`, y lo imprime 4 veces, sin haber un loop ni cambiado nada de lo que viene en `main.c`. Intenté con `fflush(stdout)`, entre otros comandos que ven el buffer sin solución.

**Comment by nmcin** [comment]
Hola,

Hay un pequeño error en el archivo de test, revisa la issue #15 .

**Comment by FdoTorres1** [comment]
Gracias! Me solucionó eso, pero sigo teniendo problemas porque no se me escribe nada en el `out.txt` como debiera según el código base del `main.c` y me sigue apareciendo el `Segmentation fault: 11`, el cual según yo se expresa en que cuando imprimo datos del `people_count` me muestra varios datos bien pero varios datos como cualquier cosa, a pesar de haber pedido la memoria de igual manera para todos esos datos.

**Comment by nmcin** [comment]
El segmentation fault termina la ejecución de tu programa, por lo que si el error ocurre antes de escribir en **out.txt** entonces logicamente no se escribirá nada en **out.txt**.
Para poder bien la causa de tu error te recomiendo correr tu programa con valgrind y ver el detalle de donde se está produciendo el error.

**Comment by FdoTorres1** [comment]
Ahora entiendo, no me está funcionando valgrind pero veré como solucionarlo, gracias.

**Comment by nmcin** [comment]
Como es tu linea de `fprintf` ?

**Comment by FdoTorres1** [comment]
Es igual a como venía inicialmente `fprintf(output_file, "INFORM %d %d\n", country_id, region_id);`

**Comment by nmcin** [comment]
Para ver tu código en más detalle lo podemos revisar por Discord.
