### ISSUE TITLE
Duda comparación de resultados 

### ISSUE THREAD

**Issue by SergioZarateG** [IIC2133-PUC/2021-1#85]
Hola,  corrí mi código con los tests entregados, pero sucede algo extraño. Con los que se encuentran en la carpeta Medium y Hard, al comparar los resultados entregados por uds y los que arroja mi implementación con _diff_ en consola, me arroja que todo el ouput.txt es diferente, sin embargo si tomo la solución que uds entregan y la copio en otro archivo.txt y vuelvo a comparar, no existen diferencias con mi output. Esto me parece super extraño y no entiendo porque está sucediendo.

**Comment by nmcin** [comment]
Hola,

Revisa que estes escribiendo bien la ruta de los archivos, estas son case-sensitive: `tests/Medium` es distinto de `tests/medium`.

**Comment by SergioZarateG** [comment]
Si he tenido cuidado con eso, de hecho hasta probé poniendo los archivos en la misma carpeta para no tener errores con el path.

**Comment by SergioZarateG** [comment]
> Hola,
> 
> Revisa que estes escribiendo bien la ruta de los archivos, estas son case-sensitive: `tests/Medium` es distinto de `tests/medium`.

Si he tenido cuidado con eso, de hecho hasta probé poniendo los archivos en la misma carpeta para no tener errores con el path.

**Comment by fadediego** [comment]
Hola!
Prueba usando diff -b
Saludos!

**Comment by SergioZarateG** [comment]
> Hola!
> Prueba usando diff -b
> Saludos!
> 

Ooh, muchas gracias ahí si me funciona correctamente.
