### ISSUE TITLE
[Duda C] Segmentation fault

### ISSUE THREAD

**Issue by Fernan-tess** [IIC2133-PUC/2021-1#87]
Hola, 

Estaba terminando de hacer el código, al ejecutarlo me empezó aparecer "Segmentation fault". Luego eliminé lo que había modificado y me sigue arrojando el mismo error, y no ejecuta el código.
Qué puede ser? He revisado e intentado varias cosas, pero me sigue arrojando el mismo error

**Comment by CarloGauss33** [comment]
Revisa con valgrind, puede que el error este ligado a funciones anteriores y que no se noto, puede ser que corriste un test diferente a veces pasadas y en dicho test ocurren condiciones borde que causan el segfault

**Comment by CrisBerriosL** [comment]
Hola! No soy ayudante, pero tambi

**Comment by CrisBerriosL** [comment]
Hola! 
No soy ayudante ni nada, pero al correr la tarea probando los distintos test me aparecieron varios Segmentation Fault. Noté que al menos en mi caso el Segmentation Fault aparecía cuando intentaba acceder a algún atributo de una Persona, pero en realidad el puntero a esa Persona era NULL. Por ejemplo, si tenia persona1, intentaba acceder a persona1.start.next, pero persona1.start era NULL. Si tu problema no nace de algo así, lo más probable es que de todas formas tenga algo que ver con intentar acceder al puntero NULL que está bloqueado (como se menciona también en las slides de Punteros).
