### ISSUE TITLE
[Tarea 0] [Pregunta noob] Tiempo ejecución

### ISSUE THREAD

**Issue by Baelfire18** [IIC2133-PUC/2021-1#88]
Hola una pregunta un poco noob.
Para calcular los tiempos de ejecución puedo eliminar los prints y printf cierto? Que mi tiempo pasa de 22 seg  a 0.131 seg cuando los saco (en los test hard).
Gracias

**Comment by CarloGauss33** [comment]
Puedes eliminar los printf. #34
