### ISSUE TITLE
[Tarea 0] Duda cambio de sintaxis de python a c

### ISSUE THREAD

**Issue by Brocoleta** [IIC2133-PUC/2021-1#9]
Como dice el enunciado debemos traspasar el código entregado en python a c, mi duda es si debemos respetar la misma sintaxis del codigo de python al traspasarlo, por ejemplo en el codigo de python los paises son listas, en mi código de c estos podrían ser structs(clases)?

**Comment by fadediego** [comment]
Hola!

El código de Python es una referencia de cómo funcionan los algoritmos que necesitarás para llevar a cabo la tarea. Sin embargo, hay built ins de Python que no tienen una contraparte en C, por lo que efectivamente tendrás que definir estructuras que consideres convenientes.
Recuerda tener en consideración la mutabilidad (o no) de los objetos para escoger la estructura adecuada.

Saludos!
