### ISSUE TITLE
[Tarea 0] Error con make

### ISSUE THREAD

**Issue by mgnavarrete** [IIC2133-PUC/2021-1#90]
Hola! al hacer el make me tira este error:
![image](https://user-images.githubusercontent.com/30879824/114058385-66454f00-9861-11eb-9245-0e3be0003d66.png)

antes me compilaba bien y no se porque ahora no me funciona.

**Comment by TrinidadVargas** [comment]
Hola, puedes intentar primero con ```make clean``` para borrar todos los archivos .o
Si esto no funciona, puedes preguntar por discord

**Comment by mgnavarrete** [comment]
no me funciono con make clean, preguntare por discord

Muchas gracias!!
