### ISSUE TITLE
Tarea Informe

### ISSUE THREAD

**Issue by perezpefaur** [IIC2133-PUC/2021-1#91]
La complejidad la calculo respecto a numero de personas no cierto? Sin importar las otras variables? Y para el calculo del paciente cero, ahi hago un analisis completo de que variables depende y su complejidad, verdad?

**Comment by jcechavarri** [comment]
Hola!
Sí, se pide la complejidad con respecto a la cantidad de personas. Para el paciente cero puedes hacer un análisis más detallado para explicar de qué depende.
Espero haberte ayudado!

**Comment by perezpefaur** [comment]
Perfecto y variables como el depth o numero de hermanos de un cierto nodo, no contarán entonces para el cálculo de complejidad.  Pregunta para el caso en que tengo:
 for (int id = 0; id < depth; id += 1){
     # algo de O(1)
   }
Entonce esto sería de complejidad O(1) para efectos de la tarea, pero O(d) (o mejor dicho O(n)), para el cálculo normal de un algoritmo.

**Comment by nmcin** [comment]
El `for` que indicas tiene complejidad O(depth), para el efecto de la tarea o de cualquier otro algoritmo. A pesar de que recorra o no a todas las personas, si hace una cantidad depth de iteraciones. Talvez puedas relacionar la cantidad total de personas con el depth, para disitntos casos posibles.
