### ISSUE TITLE
[Tarea 0] print del INFORM

### ISSUE THREAD

**Issue by mgnavarrete** [IIC2133-PUC/2021-1#92]
nose porque cuando guardo el archivo out.txt, el inform se ejectua 4 veces, estaba mirando el codgio y nose si es problema del main o de mi codigo.

![image](https://user-images.githubusercontent.com/30879824/114078504-03f74900-9877-11eb-8ed5-66da467a2e27.png)

Agregue un print para saber cuando entraba al comando desde el main y nose porque se mete 4 veces.

![image](https://user-images.githubusercontent.com/30879824/114078560-1bcecd00-9877-11eb-905d-6736f95b78e3.png)

**Comment by jcechavarri** [comment]
Hola!
No sé con que test estás probando, pero hay varios que llaman al comando INFORM más de una vez.

Por ejemplo el _easy/test_1.txt_ es:
```
5 3 5 2 3 1
5
INFORM 0 0
INFORM 0 2
INFORM 4 0
INFORM 1 4
STATISTICS 0 0 
```

Con lo que sería normal que entre al método más de una vez.
Espero haberte ayudado!
