### ISSUE TITLE
[Tarea 0] Error con valgrind

### ISSUE THREAD

**Issue by mpbascunan** [IIC2133-PUC/2021-1#93]
Hola, estoy teniendo un error raro con valgrind, en internet no he encontrado cómo solucionarlo, me aparece esto:
`error calling PR_SET_PTRACER, vgdb might block`
Sin embargo, no interfiere en el resultado de los tests, simplemente muestra eso cuando corro el programa con valgrind. Estuve leyendo en stackoverflow y decía que se producía por el uso de WSL. Aún así, quería saber si saben cómo puedo solucionarlo, o si, como no afecta el resultado de los tests, no importa que aparezca?

**Comment by nmcin** [comment]
Hola,

Como se mencionado en otras issues ese error es efectivamente de valgrind en WSL y no afecta a la ejecucción de tu programa ni al funcionamiento de valgrind (salvo en programas muy complejos que salen del contexto del curso). Puedes ignorarlo.
