### ISSUE TITLE
[Tarea 0] Análisis complejidad con arreglos

### ISSUE THREAD

**Issue by dcastillo5** [IIC2133-PUC/2021-1#94]
Hola! 
Para la parte en la que los contactos estrechos estan en arreglos significa que si tengo por ejemplo `person0->hijos = [hijo1, hijo2, hijo3]` Puedo hacer  `person = person0[2] `y olvidarme de la lógica que hay detrás de eso y tener 0(1)?.
Y otra cosa,  en el enunciado dice que _"se conoce  indice de cada ID"_,  puedo asumir que al llamar cualquier evento que tenga como parámetro una persona también tendrá como parámetro el indice de dicha persona?

**Comment by nmcin** [comment]
Hola,

Efectivamente la parte que indica que están en un arreglo funciona como indicas, sin embargo, no puedes simplemente "olvidarte de la lógica", debes dar una explicación de que complejidad tendría eso.

Para el efecto de conocer el índice de cada ID si puedes asumir lo que dices, o verlo como un oráculo al que puedes consultar en cualquier momento en O(1).
