### ISSUE TITLE
Liberando Memoria

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2133-PUC/2021-1#95]
Hola! Estoy liberando la memoria de mi programa. Intentaré no dar mucho detalle, pero en cierta parte de mi programa, este revisa si mi nodo actual tiene o un hijo o un hermano. Si esto llega a ser verdad continua liberando esos nodos.
El problema es que tengo un error del tipo:
"Conditional jump or move depends on uninitialised value(s)"
Investigue y esto sucede porque mis ifs statement depende de una variable que terminó siendo nula.

Intente también crear mis variables a comparar como nulas y luego actualizarlas según el nodo actual en el que estoy parado. Para luego compararlas en el if. Pero sigo teniendo el mismo error.
Mi pregunta es entonces, ¿Cómo puedo saber/comparar si una variable es nula o no sin directamente llamarla en el if statement? Por que llamándola en el if, se me cae el programa

Gracias :D

**Comment by TrinidadVargas** [comment]
Hola! una variable NULL tiene valor falso, por lo que con un not no debería entrar en el if. Por ejemplo:
```c
my_struct variable = NULL;
if (!variable);
```
Con esto no se debería caer tu programa y espero que esto solucione tu pregunta

**Comment by JuanDlugo** [comment]
Sii muchas gracias! Debe saltar el warning debido a otro error, pero con eso confirmo que lo que pensaba estaba bien escrito. Gracias!
