### ISSUE TITLE
[Duda C] Solución Ayudantía 2

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2133-PUC/2021-1#96]
Hola! Escribo para preguntar si estará disponible la solución y slides para la ayudantía 2 como lo estuvieron para la ayudantía 1.

**Comment by jcechavarri** [comment]
Hola!
Acabo de subir [acá](https://github.com/IIC2133-PUC/2021-1/tree/master/Ayudant%C3%ADas/Ayudanti%CC%81a%202%20-%20MergeSort%20QuickSort) las slides de la solución para la ayudantía 2. El link al video de la ayudantía debería estar disponible pronto en la página principal del repositorio! ✌️
