### ISSUE TITLE
[Administrativo] Video Clase 12/04

### ISSUE THREAD

**Issue by beatrizacuna** [IIC2133-PUC/2021-1#97]
Hola! Quería saber cuándo subirán los videos de la ayudantía 2 y la clase del lunes pasado (12/04)
Muchas gracias 😸

**Comment by TrinidadVargas** [comment]
¡Hola!
Ya está el link de la clase en el readme, pero todavía se está procesando. En un par de minutos debería estar disponible.

**Comment by beatrizacuna** [comment]
Gracias!! y la ayudantía 2? 😮

**Comment by TrinidadVargas** [comment]
Ya está arriba!
