### ISSUE TITLE
[Tarea 1] Consulta sobre filtros

### ISSUE THREAD

**Issue by chineseJack564** [IIC2133-PUC/2021-1#98]
Hola,
Despues de leerme el enunciado, se me surgio las siguientes dudas:

- Los paramentros de filtro D A G nos entregan en los archivos inputs? O lo definimos nosotros?
- En ambos filtros, hay que aplicar filtros en todos los Umbrales existente de nuestro arbol?
- En el caso de delta filter, me cuesta entender lo que signifca la cantidad de pixeles padres, son todos los que pasaron el condicion < D del Umbral anterior? Es decir, si para U>=1, pasaron el test 25 pixeles, cuando evaluo U>=2, 25 es la cantidad de pixeles padres? 
- Luego de aplicar el filtro, es necesario mantener la estructura de Max Tree no cierto?
- Como vamos a pasar el Max tree de vuelta a una imagen, nos entregaran algunas funciones? O tenemos que crearlo nosotros?

**Comment by lucas-valenzuela** [comment]
Hola,

1. Para los test, nosotros les pasaremos los parámetros 'oficiales' con los que se aplicará el filtro. Obviamente mientras pruebes tu código puedes aplicar los parámentros que quieras.

2. Claro, piensa que el filtro se aplica 'recursivamente' de los padres a los hijos.

3. Si el padre tiene un umbral U, entonces los píxeles del padre los píxeles que se cuentan son el vencindario entero, es decir, los píxeles mayores o iguales a U. Los píxeles del hijo serán todos los píxeles del vecindario del hijo, es decir, todos los píxeles igual o mayor a U+1 (de solo ese vecindario!).

4. No es necesario.

5. Ustedes deben crear las funciones.

**Comment by beatrizacuna** [comment]
Hola! Tengo una duda parecida a la consulta 3, 
![Captura de pantalla 2021-04-15 a la(s) 11 43 36](https://user-images.githubusercontent.com/48481963/114898113-d6af1b80-9ddf-11eb-8769-88338f3bad77.png)
No entiendo por qué en la segunda imagen todos los pixeles se vuelven color negro, y luego solo los de al medio se vuelven gris claro y después solo el conjunto de pixeles {7, 12, 17} se vuelve blanco.
Otra duda, el pixel 9 es parte del vecindario {7-9, 12-14, 17-19} en U => 2 porque es de color blanco?

**Comment by lucas-valenzuela** [comment]
No lo pienses directamente como que los píxeles se colorean de esa forma en cada iteración. La progresión que hicimos es para que visualicen qué ocurre según las distintas condiciones:

1. Con U >= 1, es el caso inicial, por lo que por defecto parte se le asociará con el tono negro. Esto servirá en los próximos casos, particularmente con los hijos que no cumplan con el filtro y se deben colorear como su padre (con negro en este caso).

2. Con U => 2 ocurren dos cosas:
 - Los nodos 21 y 25 no cumplen con la condición, por lo que se colorean de negro, tal como el padre
 - El nodo con vecindario {7-9, 14-14, 17-19} sí cumple la condición, por lo que 'sobrevive'

3. Con U >= 3, solo quedan los hijos {7,12,17} y {9}, ambos del padre {7-9, 14-14, 17-19}
- {7,12,17}  cumple la condición, por lo que mantiene sus colores
- {9} no cumple, por lo que colorea como su padre, en este caso con gris (U=2)

> Otra duda, el pixel 9 es parte del vecindario {7-9, 12-14, 17-19} en U => 2 porque es de color blanco?
Ve la primera imagen, ahí se ve que 9 es blanco. 9 a su vez es hijo del vecindario {7-9, 12-14, 17-19}. Recuerda que {7-9, 12-14, 17-19}  contiene un vecindario que cumple con U >= 2, por lo que incluye píxeles con un tono gris o más claro (como el blanco)

**Comment by beatrizacuna** [comment]
Entonces 9 sería parte del vecindario e hijo de este en U >= 2?

**Comment by tomasgv** [comment]
Hola! 

No me quedó muy claro si lo que se pinta en cada iteración son los **pixeles del nodo** (umbral igual al del nodo) o el **vecindario completo del nodo** (umbral mayor o igual al del nodo). 

Me parece que es lo segundo (a partir del enunciado *"Los vecindarios que no cumplan con la condición pasan a tener el color del padre"*), pero me surge una complicación con el ejemplo del primer filtro: se dice *"los vecindarios con U=1 se colorean de negro"*, entonces se colorean los pixeles del nodo, y no su vecindario completo. Además, si pintara el vecindario completo, en caso de que el nodo raíz no cumpla con las condiciones pintaría la imagen completa de negro :o

Independiente de la respuesta a lo anterior, en cada filtro se pinta lo mismo verdad? (en ambos los pixeles del nodo / en ambos el vecindario completo)

esooo gracias por leerme y perdón por la confusión uwu quizás no entendí bien la definición de vecindario

**Comment by nmcin** [comment]
Hola,

Pintar solo los pixeles del nodo o todo el umbral va a tener el mismo efecto final, si lo piensas, al pintar todo el vecindario de un color estas aplicando la regla de herencia del color del padre, sino también heredarás el color a todos los hijos que no cumplan la regla.
Para que quede claro, si pintas un nodo completo, después puedes pintar algunos de los nodos hijos de otro color si cumplieran la regla. Por eso, aunque el algún momento pintes toda la imagen en negro, puede que al aplicar el filtro en nodos más profundos vuelvas a pintar pixeles de otro color.
Y la variación del enunciado efectivamente es D.

**Comment by chineseJack564** [comment]
Hola,
No entiendo mucho lo que respondiste en lo ultimo segun yo no es lo mismo pintar un vecindario completo que los pixeles de nodo completo. Me imagino el siguiente caso.
Supongamos que para area filter, tenemos condicion G = 2 , A = 9.
Tenemos en nivel gris = 1 un vencindario de 20 pixeles, donde 10 son nivel gris 1, 10 son nivel gris 3.
Si pintamos el vecindario completo:
- Para U>=1, vamos a ver que este vecindario no comple con los reequisitos de G, por lo tatno, los 20 de vecindario pasa a tener color 0.
Si pintamos solo pixeles de nodo:
- para U>=1, pintamos los 10 de color 1 a color 0.
- para U>=3, los 10 pixles de color 3 pasan el test por lo tanto no se deben pintarse.
Entonces si lo veo asi no da lo mismo pintar todo el vecindario que pintar pixeles del nodo.
No se si entendi mal algun lado?


> Hola,
> 
> Pintar solo los pixeles del nodo o todo el umbral va a tener el mismo efecto final, si lo piensas, al pintar todo el vecindario de un color estas aplicando la regla de herencia del color del padre, sino también heredarás el color a todos los hijos que no cumplan la regla.
> Para que quede claro, si pintas un nodo completo, después puedes pintar algunos de los nodos hijos de otro color si cumplieran la regla. Por eso, aunque el algún momento pintes toda la imagen en negro, puede que al aplicar el filtro en nodos más profundos vuelvas a pintar pixeles de otro color.
> Y la variación del enunciado efectivamente es D.

**Comment by nmcin** [comment]
1 y 2. Si pintas el vecindario completo talvéz tengas que repintar algunos pixeles al aplicar el filtro en nodos más profundos, cuando pintas 2 veces debe prevalecer la aplicación mas profunda. Si pintas solo los pixeles iguales al umbral, no tendrás que repintar nada y tendrás el mismo resultado final. Esto aplica para los 2 filtros.
3. Lo pintas negro.

**Comment by Juampisaez** [comment]
Hola @nmcin 
Una duda que me quedo dando vueltas, a que se refiere el delta filter cuando se dice que si no hay variación con el nodo padre, no se aplica el filtro. Si me pudieras dar un ejemplo para poder entenderlo mejor te lo agradeceria :)

**Comment by nmcin** [comment]
Hola,

La variación entre un nodo y su padre se refiere a la diferencia entre las cantidades de pixeles de sus vecindarios. Si no hay diferencia en realidad sería un nodo vacío (sin pixeles propios), por lo que ese caso no debiera ocurrir.

**Comment by Juampisaez** [comment]
@nmcin pero eso ocurriria en teoria en el caso inicial solamente. En ese caso en particular se cambian los pixeles a negro o no?

**Comment by nmcin** [comment]
No, el caso inicial no es lo mismo, en ese caso, como no existe el padre del nodo el filtro no tiene mucho sentido, por eso el enunciado dice que no se considera. Para ese caso puedes dejar los pixeles en negro.
