### ISSUE TITLE
[Tarea 1] Duda output img_png_read_from_file

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2133-PUC/2021-1#99]
Hola! No me queda muy claro cuál es el output de la función _output img_png_read_from_file_, para poder crear el max tree. Pude entender por el código que es un arreglo de la escala de grises en el array pixeles, pero no entiendo muy bien la lógica de cómo se forma.
Si me pueden ayudar, con un ejemplo del output sería bacan para entender mejor la tarea, Gracias! :+1:

**Comment by nmcin** [comment]
Hola,

El array pixels contiene primero todos los pixeles de la primera fila, luego de la sugunda y así sucesivamente.

![image](https://user-images.githubusercontent.com/16323007/114746256-866f8500-9d1d-11eb-9651-1259f32b3151.png)
En la foto del ejemplo el array pixels sería algo así:  
```
[0,0,0,0,0,
 0,127,60,127,0,
 0,60,60,60,0
 0,60,60,60,0
 127,0,0,0,60]
```

**Comment by SebaHagedorn** [comment]
Me quedó clarísimo, gracias! :smile:

**Comment by chineseJack564** [comment]
Hola, me quedo una duda con lo que returna la funcion
![image](https://user-images.githubusercontent.com/69604944/115447879-fcc12b00-a1e6-11eb-9ea4-1e10c3e98e0b.png)
En el caso de ejemplo:
height = 5
width = 5
pixel_count = 25
estan bien esos?

**Comment by nmcin** [comment]
Si
